/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("BJ Cartridge :");
gchar *s = N_("Don't Print in Color");
gchar *s = N_("Media Type :");
gchar *s = N_("Paper Feed :");
gchar *s = N_("Custom");
gchar *s = N_("Draft");
gchar *s = N_("Standard");
gchar *s = N_("High");
gchar *s = N_("Manual");
gchar *s = N_("Standard");
gchar *s = N_("  Set ...  ");
gchar *s = N_("  Set ...  ");
gchar *s = N_("Print Quality :");
gchar *s = N_("Color Adjustment :");
gchar *s = N_("Don't Print in Color");
gchar *s = N_("Lever Position :");
gchar *s = N_("*");
gchar *s = N_("Paper Gap :");
gchar *s = N_("Defaults");
gchar *s = N_("About");
gchar *s = N_("Main");
gchar *s = N_("Paper Size :");
gchar *s = N_("Printing Type :");
gchar *s = N_("Scaling :");
gchar *s = N_("% (20-400)");
gchar *s = N_("Defaults");
gchar *s = N_("Centering");
gchar *s = N_("Borderless Pringing");
gchar *s = N_("Amount of Extension :");
gchar *s = N_("0");
gchar *s = N_("1");
gchar *s = N_("2");
gchar *s = N_("3");
gchar *s = N_("Min");
gchar *s = N_("Max");
gchar *s = N_("Copies :");
gchar *s = N_("(1-999)");
gchar *s = N_("Reverse Order");
gchar *s = N_("Collate");
gchar *s = N_("Page Setup");
gchar *s = N_("Cleaning");
gchar *s = N_("Deep Cleaning");
gchar *s = N_("Roller Cleaning");
gchar *s = N_("Nozzle Check");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("Ink Counter Reset");
gchar *s = N_("Low Ink Warning Setting");
gchar *s = N_("Power Off");
gchar *s = N_("Auto Power");
gchar *s = N_("Custom Settings");
gchar *s = N_("Quiet Mode");
gchar *s = N_("Start Status Monitor...");
gchar *s = N_("Maintenance");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Custom Paper Size");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Units :");
gchar *s = N_("Paper Size");
gchar *s = N_("mm");
gchar *s = N_("inch");
gchar *s = N_("Width :    ");
gchar *s = N_("Height :    ");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Set Print Quality");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Print Quality :");
gchar *s = N_("Standard");
gchar *s = N_("5");
gchar *s = N_("4");
gchar *s = N_("3");
gchar *s = N_("2");
gchar *s = N_("1");
gchar *s = N_("Fast");
gchar *s = N_("Fine");
gchar *s = N_("Halftoning :");
gchar *s = N_("Dithering");
gchar *s = N_("Diffusion");
gchar *s = N_("Manual Color Adjustment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Color Balance");
gchar *s = N_("  Cyan :");
gchar *s = N_("  Magenta :");
gchar *s = N_("  Yellow :");
gchar *s = N_("  Black :");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("Intensity :");
gchar *s = N_("0");
gchar *s = N_("Vivid Photo");
gchar *s = N_("Print Type :");
gchar *s = N_("Brightness :");
gchar *s = N_("Version");
gchar *s = N_("OK");
gchar *s = N_("Canon Bubble Jet Print Filter for Linux ver.2.2.0\n"
              "Copyright CANON INC. 2001-2003\n"
              "All Rights Reserved. ");
gchar *s = N_("Custom Setting");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Pause Page");
gchar *s = N_("Pause Scan");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Head position is being adjusted. Referring to printed patterns (A) to (F), \n"
              "enter the numbers of the patterns which is uniform and regular.");
gchar *s = N_("Horizontal Alignment(-3 to +7)     ");
gchar *s = N_("(A) Black");
gchar *s = N_("(B) Cyan");
gchar *s = N_("(C) Magenta");
gchar *s = N_("(D) Photo-Cyan");
gchar *s = N_("(E) Photo-Magenta");
gchar *s = N_("Bi-directional Alignment(-3 to +3)");
gchar *s = N_("(F) Bi-directional");
gchar *s = N_("Change Combination");
gchar *s = N_("Change");
gchar *s = N_("Back to Setup");
gchar *s = N_("You cannot print with the following combination :");
gchar *s = N_("Media Type :");
gchar *s = N_("Paper Size :");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("The following is recommened :");
gchar *s = N_("Media Type :");
gchar *s = N_("Paper Size :");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Click Change to use this or Back to Setup to select a different combination.");
gchar *s = N_("Change Combination");
gchar *s = N_("Change");
gchar *s = N_("Ignore");
gchar *s = N_("Back to Setup");
gchar *s = N_("You have selected the following combination :");
gchar *s = N_("Media Type :");
gchar *s = N_("Paper Size :");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Change Media Type");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("*");
gchar *s = N_("Available Media Types :");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Aligning for standard resolution. Inspect the printed\n"
              "pattern and determine the number of the pattern\n"
              "where the black and red lines appear to coincide.\n"
              "Enter this number for B1,B2");
gchar *s = N_("(-7 to +7)");
gchar *s = N_("B1 : Bi-directional Alignment:");
gchar *s = N_("B2 : Bi-directional Alignment:");
gchar *s = N_("(-7 to +7)");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Inspect the printed high-resokution pattern and\n"
              "determine the number of the pattern where the\n"
              "black and red lines appear to coincide. Enter this\n"
              "number for B1,B2");
gchar *s = N_("(-1 to +1)");
gchar *s = N_("B1 : Bi-directional Alignment:");
gchar *s = N_("(-1 to +1)");
gchar *s = N_("B2 : Bi-directional Alignment:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Print head alignment is being executed. Refering to\n"
              "the patterns printed in columns A to F, select the\n"
              "pattern that shows no flaws.\n"
              "");
gchar *s = N_("Horizontal Alignment(-3 to +7)     ");
gchar *s = N_("Column C:");
gchar *s = N_("Column B:");
gchar *s = N_("Column A:");
gchar *s = N_("Bi-directional Alignment(-5 to +5)");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Column F:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Refering to the patterns printed in columns G and H,\n"
              "select the pattern that is smoothest and has no stripes\n"
              "in area indicated by arrows.");
gchar *s = N_("Vertical Alignment(-3 to +3)");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Auto Power Setting");
gchar *s = N_("Auto Power On  :");
gchar *s = N_("Auto Power Off :");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Print Head Cleaning");
gchar *s = N_("Select Print head for cleaning.");
gchar *s = N_("All Colors");
gchar *s = N_("Black");
gchar *s = N_("Color");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Change Media Type");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("*");
gchar *s = N_("Available Media Types :");
gchar *s = N_("*");
gchar *s = N_("Custom Setting");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Ink Drying Wait Time:");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("1");
gchar *s = N_("2");
gchar *s = N_("3");
gchar *s = N_("Quiet Mode");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Use quiet mode");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Print head alignment is being executed. Refering to\n"
              "the patterns printed in columns A to F, select the\n"
              "pattern that shows no flaws.\n"
              "");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment(-3 to +7)     ");
gchar *s = N_("Bi-directional Alignment(-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Custom Setting");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Ink Drying Wait Time:");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("1");
gchar *s = N_("2");
gchar *s = N_("3");
gchar *s = N_("4");
gchar *s = N_("5");
gchar *s = N_("Low Ink Warning Setting");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Display low ink warning");
gchar *s = N_("\n"
              "Read your printer manual before enabling display of a low ink warning.\n"
              "To ensure proper display of a low ink warning, take the following precaution:\n"
              "\n"
              "Click the Ink Counter Reset button on the Maintenance tab and select the newly \n"
              "replaced ink tank whenever you have replaced any ink tank.\n"
              "\n"
              "");
gchar *s = N_("Ink Counter Reset");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Select the newly replaced ink tank and click the Execute button.The \n"
              "counter corresponding to the replaced ink tank will indicate the full level. \n"
              "This operation ensures proper display of a low ink warning.");
gchar *s = N_("Black Ink Tank");
gchar *s = N_("Color Ink Tank");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Print head alignment is being executed. Refering to\n"
              "the patterns printed in columns A to F, select the\n"
              "pattern that shows no flaws.\n"
              "");
gchar *s = N_("Horizontal Alignment(-3 to +7)     ");
gchar *s = N_("Column C:");
gchar *s = N_("Column B:");
gchar *s = N_("Column A:");
gchar *s = N_("Bi-directional Alignment(-5 to +5)");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Column F:");
gchar *s = N_("Deep Cleaning");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Select the print head for deep cleaning.");
gchar *s = N_("All Colors");
gchar *s = N_("Black");
gchar *s = N_("Color");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Print head alignment is being executed. Refering to\n"
              "the patterns printed in columns A to H, select the\n"
              "pattern that shows no flaws.\n"
              "");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment(-3 to +7)     ");
gchar *s = N_("Bi-directional Alignment(-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Print head alignment is being executed. Refering to\n"
              "the patterns printed in columns A to K, select the\n"
              "pattern that shows no flaws.\n"
              "");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment(-3 to +7)     ");
gchar *s = N_("Bi-directional Alignment(-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Refering to the patterns printed in columns L and M,\n"
              "select the pattern that is smoothest and has no stripes\n"
              "in area indicated by arrows.");
gchar *s = N_("Vertical Alignment(-3 to +3)");
gchar *s = N_("Column L:");
gchar *s = N_("Column M:");
