/*
 * Translatable strings file generated by keytext.pl.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("BJF850");
gchar *s = N_("BJF860");
gchar *s = N_("BJF870");
gchar *s = N_("BJF360");
gchar *s = N_("BJS600");
gchar *s = N_("BJS630");
gchar *s = N_("BJS6300");
gchar *s = N_("BJF900");
gchar *s = N_("BJF9000");
gchar *s = N_("BJS500");
gchar *s = N_("BJS300");
gchar *s = N_("PIXUS 550i");
gchar *s = N_("PIXUS 850i");
gchar *s = N_("PIXUS 950i");
gchar *s = N_("i250");
gchar *s = N_("i255");
gchar *s = N_("PIXUS 560i");
gchar *s = N_("PIXUS 860i");
gchar *s = N_("PIXUS 990i");
gchar *s = N_("PIXUS iP3100");
gchar *s = N_("PIXUS iP4100");
gchar *s = N_("PIXUS iP8600");
gchar *s = N_("PIXMA iP1000");
gchar *s = N_("PIXMA iP1500");
gchar *s = N_("iP2200");
gchar *s = N_("iP4200");
gchar *s = N_("iP6600D");
gchar *s = N_("iP7500");
gchar *s = N_("MP500");
gchar *s = N_("iP3300");
gchar *s = N_("MP510");
gchar *s = N_("iP4300");
gchar *s = N_("MP600");
gchar *s = N_("MP160");
gchar *s = N_("iP90");
gchar *s = N_("iP2500 series");
gchar *s = N_("iP1800 series");
gchar *s = N_("MP140 series");
gchar *s = N_("MP210 series");
gchar *s = N_("iP3500 series");
gchar *s = N_("iP4500 series");
gchar *s = N_("MP610 series");
gchar *s = N_("MP520 series");
gchar *s = N_("Color");
gchar *s = N_("Grayscale");
gchar *s = N_("Photo");
gchar *s = N_("Graphic");
gchar *s = N_("Standard");
gchar *s = N_("Linear Tone");
gchar *s = N_("Changing %s to %s is recommended.");
gchar *s = N_("Click Change to use the new combination, Ignore to use the current \n"
              "combination, or Back to Setup to select a different combination.");
gchar *s = N_("Changing %s setting is recommended.");
gchar *s = N_("Use the selector below to choose a suitable setting and click Change to use \n"
              "the new combination.");
gchar *s = N_("Click Ignore to use the current combination or Back to Setup to select a \n"
              "different combination.");
gchar *s = N_("Changing %s setting is recommended.  ");
gchar *s = N_("Use the selector below to choose a suitable setting and click Change to use\n"
              "the new combination. Click Back to Setup to select a different combination.");
gchar *s = N_("Paper Thickness Lever Position:");
gchar *s = N_("Paper Thickness Lever Position: ");
gchar *s = N_("Move the paper thickness lever %s.");
gchar *s = N_("Move the paper thickness lever %s. ");
gchar *s = N_("Media Type");
gchar *s = N_("Page Size");
gchar *s = N_("Media Type: %s cannot be used with the selected BJ Cartridge.\n"
              "Select the type of media you wish to use.");
gchar *s = N_("Plain Paper");
gchar *s = N_("Transparencies");
gchar *s = N_("Back Print Film");
gchar *s = N_("Fabric Sheet");
gchar *s = N_("High Gloss Film");
gchar *s = N_("Hagaki");
gchar *s = N_("Envelope");
gchar *s = N_("Glossy Postcard");
gchar *s = N_("High Resolution Paper");
gchar *s = N_("T-Shirt Transfers");
gchar *s = N_("Thick Paper");
gchar *s = N_("High Gloss Photo Film");
gchar *s = N_("Glossy Photo Paper");
gchar *s = N_("Glossy Photo Cards");
gchar *s = N_("Photo Paper Pro");
gchar *s = N_("Ink Jet Hagaki");
gchar *s = N_("Matte Photo Paper");
gchar *s = N_("Photo Paper Plus Glossy");
gchar *s = N_("Other Paper");
gchar *s = N_("Other Photo Paper");
gchar *s = N_("Photo Paper Plus Double Sided");
gchar *s = N_("Fine Art Photo Rag");
gchar *s = N_("Other Fine Art Paper");
gchar *s = N_("Photo Paper Plus Glossy II");
gchar *s = N_("Manual Feed");
gchar *s = N_("Auto Sheet Feeder");
gchar *s = N_("Rear Tray");
gchar *s = N_("Auto Feeder2");
gchar *s = N_("Standard Cassette");
gchar *s = N_("Optional Cassette");
gchar *s = N_("Auto Select");
gchar *s = N_("Consecutive paper feeding");
gchar *s = N_("Tractor Feeder");
gchar *s = N_("Cassette");
gchar *s = N_("Paper Feed Switch");
gchar *s = N_("Front Feeder");
gchar *s = N_("Front Tray");
gchar *s = N_("Front for Plain Paper");
gchar *s = N_("Front for Plain Paper ");
gchar *s = N_("The selected paper size cannot be used in the current Paper Source setting.\n"
              "Paper Source setting is changed to the %s.");
gchar *s = N_("Enhanced Black");
gchar *s = N_("A5 148.0x210.0mm");
gchar *s = N_("A4 210.0x297.0mm");
gchar *s = N_("A3 297.0x420.0mm");
gchar *s = N_("B5 182.0x257.0mm");
gchar *s = N_("B4 257.0x364.0mm");
gchar *s = N_("Letter 8.5\"x11\" 215.9x279.4mm");
gchar *s = N_("Legal 8.5\"x14\" 215.9x355.6mm");
gchar *s = N_("11\"x17\" 279.4x431.8mm");
gchar *s = N_("17\"x22\" 431.8x558.8mm");
gchar *s = N_("Hagaki 100.0x148.0mm");
gchar *s = N_("Comm. Env. #10 9.5\"x4.12\" 241.3x104.6mm");
gchar *s = N_("DL Env. 220.0x110.0mm");
gchar *s = N_("13.5\"x17\" 342.9x431.8mm");
gchar *s = N_("Youkei 4 235.0x105.0mm");
gchar *s = N_("Youkei 6 190.0x98.0mm");
gchar *s = N_("Letter+ 9\"x13.3\" 228.6x337.8mm");
gchar *s = N_("A4+ 223.5x355.6mm");
gchar *s = N_("A3+ 13\"x19\" 329.0x483.0mm");
gchar *s = N_("Canon 4\"x6\" 101.6x152.4mm");
gchar *s = N_("Custom...");
gchar *s = N_("Comm. Env. #10 4.12\"x9.5\" 104.6x241.3mm");
gchar *s = N_("DL Env. 110.0x220.0mm");
gchar *s = N_("Youkei 4 105.0x235.0mm");
gchar *s = N_("Youkei 6 98.0x190.0mm");
gchar *s = N_("L 89.0x127.0mm");
gchar *s = N_("2L 127.0x178.0mm");
gchar *s = N_("4\"x6\" 101.6x152.4mm");
gchar *s = N_("P 89.0x254.0mm");
gchar *s = N_("5\"x7\" 127.0x177.8mm");
gchar *s = N_("Hagaki 2 200.0x148.0mm");
gchar *s = N_("Card 2.16\"x3.58\" 55.0x91.0mm");
gchar *s = N_("Credit Card 2.13\"x3.39\" 54.0x86.0mm");
gchar *s = N_("Fine Art A4 210.0x297.0mm");
gchar *s = N_("4\"x8\" 101.6x203.2mm");
gchar *s = N_("8\"x10\" 203.2x254.0mm");
gchar *s = N_("Wide 4\"x7.1\" 101.6x180.6mm");
gchar *s = N_("mm (%s-%s)");
gchar *s = N_("inches (%s-%s)");
gchar *s = N_("Position 1");
gchar *s = N_("Position 2");
gchar *s = N_("Position 3");
gchar *s = N_("Left");
gchar *s = N_("Center");
gchar *s = N_("Right");
gchar *s = N_("Down");
gchar *s = N_("Up");
gchar *s = N_("Down");
gchar *s = N_("Up");
gchar *s = N_("Left");
gchar *s = N_("Right");
gchar *s = N_("Front");
gchar *s = N_("Back");
gchar *s = N_("Down");
gchar *s = N_("Up");
gchar *s = N_("Smoothing");
gchar *s = N_("Fine");
gchar *s = N_("Fine(Fast)");
gchar *s = N_("Banner Printing");
gchar *s = N_("Color    ");
gchar *s = N_("Black    ");
gchar *s = N_("Photo    ");
gchar *s = N_("Black/Color    ");
gchar *s = N_("Black/Photo    ");
gchar *s = N_("Photo/Color    ");
gchar *s = N_("Fit-to-Page Printing");
gchar *s = N_("Normal-size Printing");
gchar *s = N_("Scaled Printing");
gchar *s = N_("Default");
gchar *s = N_("More bright (Gamma = 1.0)");
gchar *s = N_("Light");
gchar *s = N_("Normal");
gchar *s = N_("Dark");
gchar *s = N_("Auto");
gchar *s = N_("Wide");
gchar *s = N_("Narrow");
gchar *s = N_("You have selected Borderless Printing.\n"
              "The document to be printed slightly extends off the paper.\n"
              "Print quality may deteriorate or the sheet may be stained\n"
              "at the top and bottom depending on the type of the media used.");
gchar *s = N_("Borderless printing is not recommended when %s is selected for Media Type.\n"
              "Select the type of media you wish to use.");
gchar *s = N_("The document to be printed slightly extends off the paper.\n"
              "Print quality may deteriorate or the sheet may be stained\n"
              "at the top and bottom depending on the type of the media used.");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Yes");
gchar *s = N_("No");
gchar *s = N_("Abort");
gchar *s = N_("Ignore");
gchar *s = N_("Enable");
gchar *s = N_("Disable");
gchar *s = N_("5 minutes");
gchar *s = N_("10 minutes");
gchar *s = N_("15 minutes");
gchar *s = N_("30 minutes");
gchar *s = N_("60 minutes");
gchar *s = N_("Do not start another operation until the current one has finished.");
gchar *s = N_("Were the patterns printed normally?\n"
              "\n"
              "If no patterns were printed or if the printout is noticeably blurred, click No and start again from the beginning.");
gchar *s = N_("Make sure that the printer power is on, the cable is connected properly, and the printer is online then try again.");
gchar *s = N_("Print head alignment is now complete.");
gchar *s = N_("Do not start another operation until the current one has finished.");
gchar *s = N_("Start printing nozzle check pattern? Load some paper into the sheet feeder to proceed with printing.");
gchar *s = N_("Turn the printer off?");
gchar *s = N_("Write settings to printer?");
gchar *s = N_("Cleaning paper feed rollers.\n"
              "\n"
              "You will need the special Cleaning Plate and two sheets of plain paper.\n"
              "First, wet the cleaning area of the Cleaning Plate. Wipe away any moisture in other areas on the front and back.\n"
              "Place the Cleaning Plate in the sheet feeder so that the cleaning area is towards you.\n"
              "During cleaning, the paper feed rollers will be activated 20 times. The process will take about a minute.\n"
              "\n"
              "Do you want to start roller cleaning?");
gchar *s = N_("Start cleaning?");
gchar *s = N_("Start print head deep cleaning?");
gchar *s = N_("To remove any moisture left on the paper feed rollers,\n"
              "keep the Cleaning Plate in place and insert the first sheet of plain paper into the sheet feeder.");
gchar *s = N_("With the Cleaning Plate still in place,\n"
              "insert the second sheet of plain paper into the sheet feeder to remove any remaining moisture.");
gchar *s = N_("Feed roller cleaning is complete.\n"
              "Remove the Cleaning Plate.");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Starting print head alignment to compensate for print head installation positioning error.\n"
              "\n"
              "Since alignment involves printing, make sure the printer is ready (cable connected and printer power on), \n"
              "set the printer's paper thickness lever to the left, and load a sheet of paper into the sheet feeder. \n"
              "Head alignment patterns will be printed.\n"
              "\n"
              "Start print head alignment?");
gchar *s = N_("Additional print head alignment patterns will be printed.\n"
              "\n"
              "Load another sheet of paper and click OK.");
gchar *s = N_("Execute black print head deep cleaning?");
gchar *s = N_("Execute color print head deep cleaning?");
gchar *s = N_("Cleaning paper feed rollers.\n"
              "\n"
              "First remove paper from the sheet feeder. Clicking OK will activate paper feed rollers 30 times. \n"
              "This will take about a minute and a half. When you load three sheets of plain paper according to \n"
              "the message, paper will be ejected and feed roller cleaning will be completed.\n"
              "\n"
              "Do you want to start feed roller cleaning?");
gchar *s = N_("Load three sheets of plain paper into the sheet feeder.\n");
gchar *s = N_("Feed roller cleaning is complete.");
gchar *s = N_("All Colors");
gchar *s = N_("Black");
gchar *s = N_("Black   3eBK");
gchar *s = N_("Black   PGBK");
gchar *s = N_("Color");
gchar *s = N_("Color   6C, 6M, 6Y");
gchar *s = N_("Color   6C, 6M, 6Y, 6BK");
gchar *s = N_("Color   7C, 7M, 7Y");
gchar *s = N_("Color   7C, 7M, 7Y, 7BK");
gchar *s = N_("Color   C, M, Y, BK");
gchar *s = N_("Color   C, M, Y, PC, PM, BK");
gchar *s = N_("Color   C, M, Y");
gchar *s = N_("Group 1   6BK, 6R, 6PC, 6PM");
gchar *s = N_("Group 1   7BK, 7R, 7G, 7PC, 7PM");
gchar *s = N_("Group 2   6C, 6M, 6Y");
gchar *s = N_("Group 2   7C, 7M, 7Y");
gchar *s = N_("Execute print head deep cleaning for Group 1?\n");
gchar *s = N_("Execute print head deep cleaning for Group 2?\n");
gchar *s = N_("Executes print head cleaning.\n"
              "\n"
              "Select the print head for cleaning. The ink group can be identified \n"
              "from the nozzle check pattern.");
gchar *s = N_("Do not start another operation until the cleaning has finished.\n"
              "\n"
              "After cleaning ends, execute Nozzle Check to check whether the print head nozzles have been unclogged.\n");
gchar *s = N_("Cleans clogged print head nozzles.\n"
              "\n"
              "Select the target ink group for cleaning. If you are not sure of the ink group \n"
              "for cleaning, execute Nozzle Check.\n");
gchar *s = N_("Unclogs nozzles that cannot be cleared by regular cleaning.\n"
              "\n"
              "Select the target ink group for deep cleaning. If you are not sure of the ink \n"
              "group for deep cleaning, execute Nozzle Check.\n");
gchar *s = N_("Ink Group:");
gchar *s = N_("Deep cleaning consumes much more ink than regular cleaning. Execute Deep \n"
              "Cleaning only if the nozzle condition does not improve after regular cleaning.\n"
              "\n"
              "After the deep cleaning ends, execute Nozzle Check and check whether the \n"
              "print head nozzles have been unclogged.\n");
gchar *s = N_("Cleaning consumes ink.");
gchar *s = N_("Load a sheet of A4 or letter size paper into the paper source selected by the Paper Feed Switch and click OK.\n");
gchar *s = N_("If the printed pattern resembles this pattern, \n"
              "the print head nozzles may be clogged.\n"
              "Click Cleaning.\n"
              "\n"
              "If the printed pattern does not improve, \n"
              "even after Cleaning is executed two times, \n"
              "execute Deep Cleaning.");
gchar *s = N_("Print head alignment is complete.\n"
              "To finish the alignment, click Cancel.\n"
              "\n"
              "If streaks appear on the printing side, you can prevent them from appearing by aligning the print head.\n"
              "To execute this alignment, load a sheet of paper into the sheet feeder and click OK.");
gchar *s = N_("Load a sheet of A4 or letter size paper into the sheet feeder and click OK.");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready(connect the cable and turn \n"
              "the power on), set the printer's paper thickness lever to the left and load a sheet of \n"
              "A4 or letter size, plain paper into the sheet feeder. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click OK.\n");
gchar *s = N_("Prints a pattern that lets you check whether the print head nozzles are clogged.\n"
              "\n"
              "Get the printer ready (connect the cable and turn the power on), set the printer's paper thickness lever to the left, \n"
              "load a sheet of A4 or letter size, plain paper into the sheet feeder, and click the Print Check Pattern.\n");
gchar *s = N_("Color Only");
gchar *s = N_("Black Only");
gchar *s = N_("Both Black and Color");
gchar *s = N_("Prints using only color cartridge instead of \n"
              "black cartridge.");
gchar *s = N_("Prints using only black cartridge instead of \n"
              "color cartridge only when Plain Paper is \n"
              "selected for the Media Type on the Main Tab.");
gchar *s = N_("Prints using both black and color cartridges.");
gchar *s = N_("The printer will print one sheet of pattern to start alignment automatically.\n"
              "Do not start another operation until the current one has finished.");
gchar *s = N_("Second sheet of head alignment pattern will be printed.\n"
              "\n"
              "Click OK to start printing.");
gchar *s = N_("Third sheet of head alignment pattern will be printed.\n"
              "\n"
              "Click OK to start printing.");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on), \n"
              "set the printer's paper thickness lever to the left and load a sheet of A4 or letter size, plain paper \n"
              "into the paper source selected by the Paper Feed Switch. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
gchar *s = N_("Print head alignment is complete.\n"
              "To finish the alignment, click Cancel.\n"
              "\n"
              "If streaks appear on the printing side, you can prevent them from appearing by aligning the print head.\n"
              "To execute this alignment, load a sheet of paper into the sheet feeder and click OK.");
gchar *s = N_("Prints a pattern that lets you check whether the print head nozzles are clogged.\n"
              "\n"
              "Get the printer ready (connect the cable and turn the power on), set the printer's paper \n"
              "thickness lever to the left, load a sheet of A4 or letter size, plain paper into the paper \n"
              "source selected by the Paper Feed Switch, and click the Print Check Pattern.");
gchar *s = N_("Prints a pattern that lets you check whether the print head nozzles are clogged.\n"
              "\n"
              "Load a sheet of A4 or letter size, plain paper into the sheet feeder and click the Print Check Pattern.");
gchar *s = N_("Print head alignment is complete.\n"
              "To finish the alignment, click Cancel.\n"
              "\n"
              "If streaks appear on the printing side, \n"
              "you can prevent them from appearing by aligning the print head.\n"
              "To execute this alignment, load a sheet of paper into the paper source selected \n"
              "by the Paper Feed Switch and click OK.");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on), \n"
              "set the printer's paper thickness lever to the right and load a sheet of A4 or letter size, plain paper \n"
              "into the sheet feeder. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
gchar *s = N_("If the printed pattern resembles this pattern, \n"
              "the print head nozzles may be clogged.\n"
              "Click Cleaning.\n"
              "\n"
              "If the printed pattern does not improve, \n"
              "even after Cleaning is executed two to three times, \n"
              "execute Deep Cleaning.");
gchar *s = N_("You cannot reset the ink counter because the printer is set to disable the display of low ink warning.\n"
              "\n"
              "To enable the display of a low ink warning, click the Low Ink Warning Setting button on \n"
              "the Maintenance tab of the printer driver.\n"
              "Read your printer manual before carrying out this operation.");
gchar *s = N_("Cleaning paper feed rollers.\n"
              "\n"
              "First remove paper from the rear tray.\n"
              "Clicking OK will activate paper feed rollers 30 times. This will take about a minute and a half.\n"
              "\n"
              "Do you want to start feed roller cleaning?");
gchar *s = N_("Cleaning paper feed rollers.\n"
              "\n"
              "First press the Paper Feed Switch on the printer to select the target paper source for cleaning, \n"
              "and then remove paper from the selected paper source.\n"
              "Clicking OK will activate paper feed rollers 30 times. This will take about a minute and a half.\n"
              "\n"
              "Do you want to start feed roller cleaning?");
gchar *s = N_("Confirm the operating noise of the printer has stopped, and then load three sheets of plain paper into the rear tray.\n"
              "Clicking OK will eject paper and complete feed roller cleaning.");
gchar *s = N_("Confirm the operating noise of the printer has stopped, and then load three sheets of plain paper into the selected paper source.\n"
              "Clicking OK will eject paper and complete feed roller cleaning.");
gchar *s = N_("1. Remove the paper from the sheet feeder.\n"
              "2. Fold A4 or letter size, plain paper in half, then unfold the paper.\n"
              "3. With the ridge of the crease facing down, load the paper into the sheet feeder.\n"
              "4. Click Execute.");
gchar *s = N_("1. Remove the paper from the rear tray.\n"
              "2. Fold A4 or letter size, plain paper in half, then unfold the paper.\n"
              "3. With the ridge of the crease facing down, load the paper into the rear tray.\n"
              "4. Click Execute.");
gchar *s = N_("Prints a pattern that lets you check whether the print head nozzles are clogged.\n"
              "\n"
              "Get the printer ready (connect the cable and turn the power on), set the printer's paper thickness \n"
              "lever to the left, load a sheet of A4 or letter size, plain paper into the rear tray, and click \n"
              "the Print Check Pattern.");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on), \n"
              "set the printer's paper thickness lever to the left and load two sheets of A4 or letter size, plain \n"
              "paper into the rear tray. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
gchar *s = N_("Starting automatic print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on), \n"
              "load one sheet of A4 or letter size, plain paper into the sheet feeder and click Print Head Alignment. \n"
              "\n"
              "To carry out manual head alignment, click Cancel.\n"
              "Next, click Custom Settings on the Maintenance tab of the printer driver, check Align heads manually, \n"
              "and click Send. Then try again.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
gchar *s = N_("Starting automatic print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on), \n"
              "load two sheets of A4 or letter size, Matte Photo Paper (MP-101) into the rear tray and click Print \n"
              "Head Alignment. \n"
              "\n"
              "To carry out manual head alignment, click Cancel.\n"
              "Next, click Custom Settings on the Maintenance tab of the printer driver, check Align heads manually, \n"
              "and click Send. Then try again.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
gchar *s = N_("Load a sheet of A4 or letter size, plain paper into the rear tray and click OK.");
gchar *s = N_("The printer will print two sheets of pattern to start alignment automatically.\n"
              "Do not start another operation until the current one has finished.");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on) \n"
              "and load four sheets of A4 or letter size, plain paper into the paper source selected by the Paper \n"
              "Feed Switch. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
gchar *s = N_("Fourth sheet of head alignment pattern will be printed.\n"
              "\n"
              "Click OK to start printing.");
gchar *s = N_("Prints a pattern that lets you check whether the print head nozzles are clogged.\n"
              "\n"
              "Load a sheet of A4 or letter size, plain paper into the paper source selected by the Paper Feed Switch \n"
              "and click the Print Check Pattern.");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on), \n"
              "set the printer's paper thickness lever to the left and load a sheet of A4 or letter size, plain paper \n"
              "into the rear tray. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on) \n"
              "and load a sheet of A4 or letter size, plain paper into the paper source selected by the Paper \n"
              "Feed Switch. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
gchar *s = N_("Load a sheet of A4 or letter size paper into the rear tray and click OK.");
gchar *s = N_("Print head alignment is complete.\n"
              "To finish the alignment, click Cancel.\n"
              "\n"
              "If streaks appear on the printing side, you can prevent them from appearing by aligning the print head.\n"
              "To execute this alignment, load a sheet of paper into the rear tray and click OK.");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on) \n"
              "and load three sheets of A4 or letter size, plain paper into the paper source selected by the Paper \n"
              "Feed Switch. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on), \n"
              "set the printer's paper thickness lever to the left and load a sheet of A4 or letter size, plain paper \n"
              "into the sheet feeder. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Print Alignment Value.");
