/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ui_window (void);
GtkWidget* create_user_size_dialog (void);
GtkWidget* create_quality_dialog (void);
GtkWidget* create_color_dialog (void);
GtkWidget* create_version_dialog (void);
GtkWidget* create_special_dialog (void);
GtkWidget* create_regi_dialog (void);
GtkWidget* create_mediasize_illegal_dialog (void);
GtkWidget* create_mediasize_recommend_dialog (void);
GtkWidget* create_mediatype_dialog (void);
GtkWidget* create_F360regi1_dialog (void);
GtkWidget* create_F360regi2_dialog (void);
GtkWidget* create_S600regi1_dialog (void);
GtkWidget* create_S600regi2_dialog (void);
GtkWidget* create_autopower_dialog (void);
GtkWidget* create_cleaning_dialog (void);
GtkWidget* create_mediaborder_dialog (void);
GtkWidget* create_drylevel3_dialog (void);
GtkWidget* create_quiet_dialog (void);
GtkWidget* create_F900regi_dialog (void);
GtkWidget* create_drylevel5_dialog (void);
GtkWidget* create_ink_warning_dialog (void);
GtkWidget* create_ink_reset_dialog (void);
GtkWidget* create_PX550Iregi_dialog (void);
GtkWidget* create_refreshing_dialog (void);
GtkWidget* create_PX950Iregi_dialog (void);
GtkWidget* create_PX850Iregi1_dialog (void);
GtkWidget* create_PX850Iregi2_dialog (void);
GtkWidget* create_PX990Iregi_dialog (void);
GtkWidget* create_PX990Iauto_regi_dialog (void);
GtkWidget* create_PX860Iregi1_dialog (void);
GtkWidget* create_PX860Iregi2_dialog (void);
GtkWidget* create_pattern_check_dialog (void);
GtkWidget* create_nozzle_check_dialog (void);
GtkWidget* create_head_alignment_dialog (void);
GtkWidget* create_plate_cleaning_dialog (void);
GtkWidget* create_ip8600regi_dialog (void);
GtkWidget* create_deep_cleaning_dialog (void);
