/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("BJ Cartridge:");
gchar *s = N_("Grayscale Printing");
gchar *s = N_("Media Type:");
gchar *s = N_("Paper Source:");
gchar *s = N_("  Set ...  ");
gchar *s = N_("  Set ...  ");
gchar *s = N_("Print Quality:");
gchar *s = N_("Color/Intensity:");
gchar *s = N_("High");
gchar *s = N_("Standard");
gchar *s = N_("Fast");
gchar *s = N_("Custom");
gchar *s = N_("Auto");
gchar *s = N_("Manual");
gchar *s = N_("Grayscale Printing");
gchar *s = N_("Lever Position:");
gchar *s = N_("*");
gchar *s = N_("Paper Gap:");
gchar *s = N_("Defaults");
gchar *s = N_("About");
gchar *s = N_("Main");
gchar *s = N_("Page Size:");
gchar *s = N_("Page Layout:");
gchar *s = N_("Scaling:");
gchar *s = N_("% (20-400)");
gchar *s = N_("Centering");
gchar *s = N_("Borderless Printing");
gchar *s = N_("Amount of Extension:");
gchar *s = N_("0");
gchar *s = N_("1");
gchar *s = N_("2");
gchar *s = N_("3");
gchar *s = N_("Min");
gchar *s = N_("Max");
gchar *s = N_("Automatic Duplex Printing");
gchar *s = N_("Staple Side:");
gchar *s = N_("Long-side stapling");
gchar *s = N_("Short-side stapling");
gchar *s = N_("Copies:");
gchar *s = N_("(1-999)");
gchar *s = N_("Print from Last Page");
gchar *s = N_("Collate");
gchar *s = N_("Defaults");
gchar *s = N_("Page Setup");
gchar *s = N_("Cleaning");
gchar *s = N_("Deep Cleaning");
gchar *s = N_("Roller Cleaning");
gchar *s = N_("Bottom Plate Cleaning");
gchar *s = N_("Nozzle Check");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("Ink Counter Reset");
gchar *s = N_("Low Ink Warning Setting");
gchar *s = N_("Ink Cartridge Settings");
gchar *s = N_("Power Off");
gchar *s = N_("Auto Power");
gchar *s = N_("Custom Settings");
gchar *s = N_("Quiet Mode");
gchar *s = N_("View Printer Status...");
gchar *s = N_("Maintenance");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Custom Paper Size");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Units:");
gchar *s = N_("Paper Size");
gchar *s = N_("mm");
gchar *s = N_("inches");
gchar *s = N_("Width:    ");
gchar *s = N_("Height:     ");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Custom");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Quality:");
gchar *s = N_("Standard");
gchar *s = N_("3");
gchar *s = N_("5");
gchar *s = N_("4");
gchar *s = N_("3");
gchar *s = N_("2");
gchar *s = N_("1");
gchar *s = N_("Fast");
gchar *s = N_("Fine");
gchar *s = N_("Halftoning:");
gchar *s = N_("Dither");
gchar *s = N_("Diffusion");
gchar *s = N_("Manual Color Adjustment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Color Balance");
gchar *s = N_("  Yellow:");
gchar *s = N_("  Black:");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("  Cyan:");
gchar *s = N_("  Magenta:");
gchar *s = N_("Intensity:");
gchar *s = N_("0");
gchar *s = N_("Vivid Photo");
gchar *s = N_("Print Type:");
gchar *s = N_("Brightness:");
gchar *s = N_("About");
gchar *s = N_("OK");
gchar *s = N_("Canon Inkjet Printer Driver Ver.2.70 for Linux\n"
              "Copyright CANON INC. 2001-2007\n"
              "All Rights Reserved. ");
gchar *s = N_("Custom Settings");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Pause Page");
gchar *s = N_("Pause Scan");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields, for columns A to F.");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("A. Black:");
gchar *s = N_("B. Cyan:");
gchar *s = N_("C. Magenta:");
gchar *s = N_("D. Photo Cyan:");
gchar *s = N_("E. Photo Magenta:");
gchar *s = N_("Bi-directional Alignment (-3 to +3)");
gchar *s = N_("F. Bi-directional:");
gchar *s = N_("Change Combination");
gchar *s = N_("Change");
gchar *s = N_("Back to Setup");
gchar *s = N_("You cannot print with the following combination:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Page Size:");
gchar *s = N_("Media Type:");
gchar *s = N_("The following is recommended:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Page Size:");
gchar *s = N_("Media Type:");
gchar *s = N_("Click Change to use this, or Back to Setup to select a different combination.");
gchar *s = N_("Change Combination");
gchar *s = N_("Change");
gchar *s = N_("Ignore");
gchar *s = N_("Back to Setup");
gchar *s = N_("You have selected the following combination:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Page Size:");
gchar *s = N_("Media Type:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Change Media Type");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("*");
gchar *s = N_("Available Media Types:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Aligning for standard resolution. Inspect the printed\n"
              "pattern and determine the number of the pattern\n"
              "where the upper and lower lines appear to coincide.\n"
              "Enter this number for B1, B2.");
gchar *s = N_("(-7 to +7)");
gchar *s = N_("B1. Bi-directional Alignment:");
gchar *s = N_("B2. Bi-directional Alignment:");
gchar *s = N_("(-7 to +7)");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Inspect the printed high-resolution pattern and\n"
              "determine the number of the pattern where the\n"
              "upper and lower lines appear to coincide. Enter this\n"
              "number for B1, B2.");
gchar *s = N_("(-1 to +1)");
gchar *s = N_("B1. Bi-directional Alignment:");
gchar *s = N_("(-1 to +1)");
gchar *s = N_("B2. Bi-directional Alignment:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields, for columns A to F.");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column C:");
gchar *s = N_("Column B:");
gchar *s = N_("Column A:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Column F:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and fill in the fields for columns G and H \n"
              "with the number of the pattern that is smoothest and has no stripes in \n"
              "the areas indicated by arrows.");
gchar *s = N_("Vertical Alignment (-3 to +3)");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Auto Power Settings");
gchar *s = N_("Auto Power On:");
gchar *s = N_("Auto Power Off:");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Print Head Cleaning");
gchar *s = N_("Select print head for cleaning.");
gchar *s = N_("Print Head:");
gchar *s = N_("All Colors");
gchar *s = N_("Black");
gchar *s = N_("Color");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Change Media Type");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("*");
gchar *s = N_("Available Media Types:");
gchar *s = N_("*");
gchar *s = N_("Custom Settings");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Prevent paper abrasion");
gchar *s = N_("Align heads manually");
gchar *s = N_("Ink Drying Wait Time:");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("1");
gchar *s = N_("2");
gchar *s = N_("3");
gchar *s = N_("Quiet Mode");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Use quiet mode");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields, for columns A to F.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Custom Settings");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Prevent paper abrasion");
gchar *s = N_("Align heads manually");
gchar *s = N_("Ink Drying Wait Time:");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("1");
gchar *s = N_("2");
gchar *s = N_("3");
gchar *s = N_("4");
gchar *s = N_("5");
gchar *s = N_("Low Ink Warning Setting");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Display low ink warning");
gchar *s = N_("Read your printer manual for details about low ink warnings.");
gchar *s = N_("To ensure proper display of a low ink warning, the following operation is \n"
              "required:\n"
              "");
gchar *s = N_("When you have replaced an ink tank with a new one, always click \n"
              "the Ink Counter Reset button on the Maintenance tab of the printer driver \n"
              "and select the new ink tank.");
gchar *s = N_("Ink Counter Reset");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Select the newly replaced ink tank and click the Execute button.\n"
              "");
gchar *s = N_("The counter corresponding to the replaced ink tank will indicate \n"
              "the tank is full. This operation ensures proper display of a low \n"
              "ink warning.");
gchar *s = N_("Black Ink Tank");
gchar *s = N_("Color Ink Tank");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields, for columns A to F.");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column C:");
gchar *s = N_("Column B:");
gchar *s = N_("Column A:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Column F:");
gchar *s = N_("Deep Cleaning");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Deep Cleaning requires a lot of ink. Execute it only when you have not resolved the print head problem by trying cleaning several times.\n"
              "\n"
              "Select the print head for deep cleaning.");
gchar *s = N_("Print Head:");
gchar *s = N_("All Colors");
gchar *s = N_("Black");
gchar *s = N_("Color");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter the \n"
              "pattern number of the pattern with the least amount of streaking \n"
              "in the fields for columns A to H.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter the \n"
              "pattern number of the pattern with the least amount of streaking in \n"
              "the fields for columns A to K.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and fill in the fields for columns L and M with \n"
              "the number of the pattern that is smoothest and has no stripes in \n"
              "the areas indicated by arrows.");
gchar *s = N_("Vertical Alignment (-3 to +3)");
gchar *s = N_("Column L:");
gchar *s = N_("Column M:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter the \n"
              "pattern number of the pattern with the least amount of streaking in the \n"
              "fields for columns A to J.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column F:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column G:");
gchar *s = N_("Simple Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("First execute print head alignment manually. Then examine the printed \n"
              "patterns, and enter the pattern number of the pattern with the least amount \n"
              "of streaking in each field.");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column F:");
gchar *s = N_("Column E:");
gchar *s = N_("Column C:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column I:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in \n"
              "the fields for columns A to L.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column F:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Column L:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and fill in the fields for columns M and N \n"
              "with the number of the pattern that is smoothest and has no stripes in \n"
              "the areas indicated by arrows.");
gchar *s = N_("Vertical Alignment (-3 to +3)");
gchar *s = N_("Column M:");
gchar *s = N_("Column N:");
gchar *s = N_("Pattern Check");
gchar *s = N_("Exit");
gchar *s = N_("Cleaning");
gchar *s = N_("Which of the following patterns does the printed pattern most closely resemble?");
gchar *s = N_("The print head nozzles are not clogged.\n"
              "If the printed pattern resembles this pattern, you can \n"
              "use the printer immediately.\n"
              "Click Exit.\n"
              "");
gchar *s = N_("If the printed pattern resembles this pattern, \n"
              "the print head nozzles may be clogged.\n"
              "Click Cleaning.\n"
              "\n"
              "If the printed pattern does not improve, \n"
              "even after Cleaning is executed two times, \n"
              "execute Deep Cleaning.");
gchar *s = N_("Nozzle Check");
gchar *s = N_("Print Check Pattern");
gchar *s = N_("Cancel");
gchar *s = N_("Prints a pattern that lets you check whether the print head nozzles are clogged.\n"
              "\n"
              "Load a sheet of A4 or letter size, plain paper into the paper source selected \n"
              "by the Paper Feed Switch and click the Print Check Pattern.");
gchar *s = N_("Start Print Head Alignment");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("Check Setting");
gchar *s = N_("Cancel");
gchar *s = N_("Starting automatic print head alignment.\n"
              "\n"
              "Since the alignment involves printing, get the printer ready (connect the cable and turn the power on), \n"
              "load one sheet of A4 or letter size, plain paper into the sheet feeder and click Print Head Alignment.\n"
              "\n"
              "To carry out manual head alignment, click Cancel.\n"
              "Next, click Custom Settings on the Maintenance tab of the printer driver, check Align heads manually, \n"
              "and click Send. Then try again.\n"
              "\n"
              "To print and check the current setting, click Check Setting.");
gchar *s = N_("Bottom Plate Cleaning");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Executes Bottom Plate Cleaning.\n"
              "\n"
              "1. Remove the paper from the sheet feeder.\n"
              "2. Fold A4 or letter size, plain paper in half. Unfold the paper, and load the paper into \n"
              "the sheet feeder with the ridge of the crease facing down. Then click Execute.");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter the \n"
              "pattern number of the pattern with the least amount of streaking in \n"
              "the fields for columns A to K.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Column H:");
gchar *s = N_("Deep Cleaning");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Unclogs nozzles that cannot be cleared by regular cleaning.\n"
              "\n"
              "Deep cleaning consumes much more ink than regular cleaning. Execute Deep \n"
              "Cleaning only if the nozzle condition does not improve after regular cleaning.\n"
              "\n"
              "After the deep cleaning ends, execute Nozzle Check and check whether the \n"
              "print head nozzles have been unclogged.");
gchar *s = N_("Changing the Paper Source");
gchar *s = N_("Change");
gchar *s = N_("Back to Setup");
gchar *s = N_("The selected paper size cannot be used in the current Paper Source setting.\n"
              "Paper Source setting is changed to the Auto Sheet Feeder.");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in \n"
              "the fields for columns A to J.");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Adjustment in Columns A to F (-3 to +7)");
gchar *s = N_("Adjustment in Columns G to J (-5 to +5)");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Column F:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and enter the pattern number of the pattern \n"
              "with the least amount of streaking in the fields for columns K to P.");
gchar *s = N_("Column O:");
gchar *s = N_("Column P:");
gchar *s = N_("Column K:");
gchar *s = N_("Adjustment in Columns K to N (-5 to +5)");
gchar *s = N_("Column L:");
gchar *s = N_("Column M:");
gchar *s = N_("Column N:");
gchar *s = N_("Adjustment in Columns O and P (-3 to +3)");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in \n"
              "the fields for columns A to G.");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Adjustment in Columns A to E (-3 to +7)");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Adjustment in Columns F and G (-5 to +5)");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and enter the pattern number of the pattern \n"
              "with the least amount of streaking in the fields for columns H to J.");
gchar *s = N_("Column J:");
gchar *s = N_("Adjustment in Columns H and I (-5 to +5)");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Adjustment in Column J (-3 to +3)");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in \n"
              "the fields for columns A to H.");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Adjustment in Columns A to F (-3 to +7)");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Column F:");
gchar *s = N_("Adjustment in Columns G and H (-5 to +5)");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and enter the pattern number of the pattern \n"
              "with the least amount of streaking in the fields for columns I to M.");
gchar *s = N_("Column M:");
gchar *s = N_("Adjustment in Columns I to L (-5 to +5)");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Column L:");
gchar *s = N_("Adjustment in Column M (-3 to +3)");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields for columns A to L.");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Column L:");
gchar *s = N_("Adjustment in Columns A to F (-5 to +5)");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Column F:");
gchar *s = N_("Adjustment in Columns G to L (-5 to +5)");
gchar *s = N_("Change Combination");
gchar *s = N_("Change");
gchar *s = N_("Back to Setup");
gchar *s = N_("You cannot print with the following combination:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Page Size:");
gchar *s = N_("Media Type:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Ink Cartridge Settings");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Select the ink cartridge for printing.");
gchar *s = N_("Ink Cartridge:");
gchar *s = N_("*");
gchar *s = N_("Bottom Plate Cleaning");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Starting Bottom Plate Cleaning to prevent paper smudges during printing.\n"
              "\n"
              "This operation needs a sheet of A4 or letter size, plain paper. Follow these directions to execute Bottom Plate Cleaning.");
gchar *s = N_("1. Remove the paper from the sheet feeder.\n"
              "2. Fold A4 or letter size, plain paper in half, then unfold the paper.\n"
              "3. With the ridge of the crease facing down, load the paper into the sheet feeder.\n"
              "4. Click Execute.");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in \n"
              "the fields for columns A to F.");
gchar *s = N_("Adjustment in Columns A to C (-3 to +7)");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column F:");
gchar *s = N_("Adjustment in Columns D to F (-5 to +5)");
gchar *s = N_("Column E:");
gchar *s = N_("Column D:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and enter the pattern number of the pattern \n"
              "with the least amount of streaking in the fields for columns G to L.");
gchar *s = N_("Adjustment in Columns G to J (-5 to +5)");
gchar *s = N_("Column J:");
gchar *s = N_("Column I:");
gchar *s = N_("Column H:");
gchar *s = N_("Column G:");
gchar *s = N_("Adjustment in Columns K and L (-3 to +3)");
gchar *s = N_("Column K:");
gchar *s = N_("Column L:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and enter the pattern number of the most \n"
              "even pattern for columns M and N.");
gchar *s = N_("Adjustment in Columns M and N (-2 to +2)");
gchar *s = N_("Column N:");
gchar *s = N_("Column M:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in \n"
              "the fields for columns A to K.");
gchar *s = N_("Adjustment in Columns A to E (-3 to +7)");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Adjustment in Columns F to K (-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and fill in the fields for columns L and M with \n"
              "the number of the pattern that is smoothest and has no stripes in the areas \n"
              "indicated by arrows.");
gchar *s = N_("Adjustment in Columns L and M (-3 to +3)");
gchar *s = N_("Column M:");
gchar *s = N_("Column L:");
gchar *s = N_("Manual Color Adjustment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Vivid Photo");
gchar *s = N_("Color Mode:");
gchar *s = N_("Color Balance");
gchar *s = N_("  Yellow:");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("  Cyan:");
gchar *s = N_("  Magenta:");
gchar *s = N_("High ");
gchar *s = N_("High ");
gchar *s = N_("High ");
gchar *s = N_("Low");
gchar *s = N_("Low");
gchar *s = N_("Low");
gchar *s = N_("Intensity:");
gchar *s = N_("0");
gchar *s = N_("Dark ");
gchar *s = N_("High ");
gchar *s = N_("0");
gchar *s = N_("Contrast:");
gchar *s = N_("Light ");
gchar *s = N_("Low");
gchar *s = N_("Brightness:");
gchar *s = N_("Auto Power Settings");
gchar *s = N_("Auto Power Off");
gchar *s = N_("Using AC Adapter:");
gchar *s = N_("Using Battery:");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute print head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in \n"
              "the fields for columns A to K.");
gchar *s = N_("Horizontal Alignment (-3 to +7)");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
