/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("BJ Cartridge:");
gchar *s = N_("Grayscale Printing");
gchar *s = N_("Media Type:");
gchar *s = N_("Paper Source:");
gchar *s = N_("  Set ...  ");
gchar *s = N_("  Set ...  ");
gchar *s = N_("Print Quality:");
gchar *s = N_("Color Adjustment:");
gchar *s = N_("High");
gchar *s = N_("Standard");
gchar *s = N_("Draft");
gchar *s = N_("Custom");
gchar *s = N_("Auto");
gchar *s = N_("Manual");
gchar *s = N_("Grayscale Printing");
gchar *s = N_("Lever Position:");
gchar *s = N_("*");
gchar *s = N_("Paper Gap:");
gchar *s = N_("Defaults");
gchar *s = N_("About");
gchar *s = N_("Main");
gchar *s = N_("Page Size:");
gchar *s = N_("Printing Type:");
gchar *s = N_("Scaling:");
gchar *s = N_("% (20-400)");
gchar *s = N_("Centering");
gchar *s = N_("Borderless Printing");
gchar *s = N_("Amount of Extension:");
gchar *s = N_("0");
gchar *s = N_("1");
gchar *s = N_("2");
gchar *s = N_("3");
gchar *s = N_("Min");
gchar *s = N_("Max");
gchar *s = N_("Copies:");
gchar *s = N_("(1-999)");
gchar *s = N_("Reverse Order");
gchar *s = N_("Collate");
gchar *s = N_("Defaults");
gchar *s = N_("Page Setup");
gchar *s = N_("Cleaning");
gchar *s = N_("Deep Cleaning");
gchar *s = N_("Roller Cleaning");
gchar *s = N_("Bottom Plate Cleaning");
gchar *s = N_("Nozzle Check");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("Ink Counter Reset");
gchar *s = N_("Low Ink Warning Setting");
gchar *s = N_("Power Off");
gchar *s = N_("Auto Power");
gchar *s = N_("Custom Settings");
gchar *s = N_("Quiet Mode");
gchar *s = N_("Start Status Monitor...");
gchar *s = N_("Maintenance");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Custom Paper Size");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Units:");
gchar *s = N_("Paper Size");
gchar *s = N_("mm");
gchar *s = N_("inches");
gchar *s = N_("Width:    ");
gchar *s = N_("Height:     ");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Set Print Quality");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Quality:");
gchar *s = N_("Standard");
gchar *s = N_("5");
gchar *s = N_("4");
gchar *s = N_("3");
gchar *s = N_("2");
gchar *s = N_("1");
gchar *s = N_("Fast");
gchar *s = N_("Fine");
gchar *s = N_("Halftoning:");
gchar *s = N_("Dither");
gchar *s = N_("Diffusion");
gchar *s = N_("Manual Color Adjustment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Color Balance");
gchar *s = N_("  Yellow:");
gchar *s = N_("  Black:");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("  Cyan:");
gchar *s = N_("  Magenta:");
gchar *s = N_("Intensity:");
gchar *s = N_("0");
gchar *s = N_("Vivid Photo");
gchar *s = N_("Print Type:");
gchar *s = N_("Brightness:");
gchar *s = N_("About");
gchar *s = N_("OK");
gchar *s = N_("Canon Bubble Jet Print Filter for Linux Ver.2.50\n"
              "Copyright CANON INC. 2001-2005\n"
              "All Rights Reserved. ");
gchar *s = N_("Custom Settings");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Pause Page");
gchar *s = N_("Pause Scan");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Execute head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields for columns A to F.");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("A. Black:");
gchar *s = N_("B. Cyan:");
gchar *s = N_("C. Magenta:");
gchar *s = N_("D. Photo Cyan:");
gchar *s = N_("E. Photo Magenta:");
gchar *s = N_("Bi-directional Alignment (-3 to +3)");
gchar *s = N_("F. Bi-directional:");
gchar *s = N_("Change Combination");
gchar *s = N_("Change");
gchar *s = N_("Back to Setup");
gchar *s = N_("You cannot print with the following combination:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Page Size:");
gchar *s = N_("Media Type:");
gchar *s = N_("The following is recommended:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Page Size:");
gchar *s = N_("Media Type:");
gchar *s = N_("Click Change to use this or Back to Setup to select a different combination.");
gchar *s = N_("Change Combination");
gchar *s = N_("Change");
gchar *s = N_("Ignore");
gchar *s = N_("Back to Setup");
gchar *s = N_("You have selected the following combination:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Page Size:");
gchar *s = N_("Media Type:");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("*");
gchar *s = N_("Change Media Type");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("*");
gchar *s = N_("Available Media Types:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Aligning for standard resolution. Inspect the printed\n"
              "pattern and determine the number of the pattern\n"
              "where the upper and lower lines appear to coincide.\n"
              "Enter this number for B1, B2.");
gchar *s = N_("(-7 to +7)");
gchar *s = N_("B1. Bi-directional Alignment:");
gchar *s = N_("B2. Bi-directional Alignment:");
gchar *s = N_("(-7 to +7)");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Inspect the printed high-resolution pattern and\n"
              "determine the number of the pattern where the\n"
              "upper and lower lines appear to coincide. Enter this\n"
              "number for B1, B2.");
gchar *s = N_("(-1 to +1)");
gchar *s = N_("B1. Bi-directional Alignment:");
gchar *s = N_("(-1 to +1)");
gchar *s = N_("B2. Bi-directional Alignment:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Execute head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields for columns A to F.");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column C:");
gchar *s = N_("Column B:");
gchar *s = N_("Column A:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Column F:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and fill in the fields for columns G and H with the number of the pattern that is smoothest and has no stripes in areas indicated by arrows.");
gchar *s = N_("Vertical Alignment (-3 to +3)");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Auto Power Settings");
gchar *s = N_("Auto Power On:");
gchar *s = N_("Auto Power Off:");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Print Head Cleaning");
gchar *s = N_("Select print head for cleaning.");
gchar *s = N_("Print Head:");
gchar *s = N_("All Colors");
gchar *s = N_("Black");
gchar *s = N_("Color");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Change Media Type");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("*");
gchar *s = N_("Available Media Types:");
gchar *s = N_("*");
gchar *s = N_("Custom Settings");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Prevent paper abrasion");
gchar *s = N_("Align heads manually");
gchar *s = N_("Ink Drying Wait Time:");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("1");
gchar *s = N_("2");
gchar *s = N_("3");
gchar *s = N_("Quiet Mode");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Use quiet mode");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Execute head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields for columns A to F.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Custom Settings");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Prevent paper abrasion");
gchar *s = N_("Align heads manually");
gchar *s = N_("Ink Drying Wait Time:");
gchar *s = N_("Short");
gchar *s = N_("Long");
gchar *s = N_("1");
gchar *s = N_("2");
gchar *s = N_("3");
gchar *s = N_("4");
gchar *s = N_("5");
gchar *s = N_("Low Ink Warning Setting");
gchar *s = N_("Send");
gchar *s = N_("Cancel");
gchar *s = N_("Defaults");
gchar *s = N_("Display low ink warning");
gchar *s = N_("Read your printer manual for details about a low ink warning.");
gchar *s = N_("To ensure proper display of a low ink warning, the following operation is \n"
              "required:\n"
              "");
gchar *s = N_("When you have replaced any ink tank with a new one, always click the Ink \n"
              "Counter Reset button on the Maintenance tab of the printer driver and \n"
              "select the new ink tank.");
gchar *s = N_("Ink Counter Reset");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Select the newly replaced ink tank and click the Execute button.\n"
              "");
gchar *s = N_("The counter corresponding to the replaced ink tank will indicate the full \n"
              "level. This operation ensures proper display of a low ink warning.\n"
              "");
gchar *s = N_("Black Ink Tank");
gchar *s = N_("Color Ink Tank");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields for columns A to F.");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column C:");
gchar *s = N_("Column B:");
gchar *s = N_("Column A:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Column F:");
gchar *s = N_("Deep Cleaning");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Deep Cleaning requires a lot of ink. Execute it when doing cleaning\n"
              "several times does not resolve the print head problem.\n"
              "\n"
              "Select the print head for deep cleaning.\n"
              "");
gchar *s = N_("Print Head:");
gchar *s = N_("All Colors");
gchar *s = N_("Black");
gchar *s = N_("Color");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Execute head alignment. Examine the printed patterns, and enter the pattern number of the pattern with the least amount of streaking in the fields for columns A to H.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute head alignment. Examine the printed patterns, and enter the \n"
              "pattern number of the pattern with the least amount of streaking in the \n"
              "fields for columns A to K.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and fill in the fields for columns L and M \n"
              "with the number of the pattern that is smoothest and has no stripes in \n"
              "areas indicated by arrows.");
gchar *s = N_("Vertical Alignment (-3 to +3)");
gchar *s = N_("Column L:");
gchar *s = N_("Column M:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute head alignment. Examine the printed patterns, and enter the pattern number of the pattern with the least amount of streaking in the fields for columns A to J.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column F:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column G:");
gchar *s = N_("Simple Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("First execute head alignment manually. Then examine the printed patterns, and enter the pattern number of the pattern with the least amount of streaking in each field.");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column F:");
gchar *s = N_("Column E:");
gchar *s = N_("Column C:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column I:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute head alignment. Examine the printed patterns, and enter \n"
              "the pattern number of the pattern with the least amount of streaking in the \n"
              "fields for columns A to L.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column F:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column G:");
gchar *s = N_("Column H:");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Column L:");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Examine the printed patterns, and fill in the fields for columns M and N \n"
              "with the number of the pattern that is smoothest and has no stripes in \n"
              "areas indicated by arrows.");
gchar *s = N_("Vertical Alignment (-3 to +3)");
gchar *s = N_("Column M:");
gchar *s = N_("Column N:");
gchar *s = N_("Pattern Check");
gchar *s = N_("Exit");
gchar *s = N_("Cleaning");
gchar *s = N_("Which of the following patterns does the printed pattern most closely resemble?");
gchar *s = N_("The print head nozzles are not clogged.\n"
              "If the printed pattern resembles this pattern, you can \n"
              "use the printer immediately.\n"
              "Click Exit.\n"
              "");
gchar *s = N_("If the printed pattern resembles this pattern, the \n"
              "print head nozzles may be clogged.\n"
              "Click Cleaning.\n"
              "\n"
              "If the printed pattern does not improve even \n"
              "after Cleaning is executed two to three times, \n"
              "execute Deep Cleaning.");
gchar *s = N_("Nozzle Check");
gchar *s = N_("Print Check Pattern");
gchar *s = N_("Cancel");
gchar *s = N_("Prints pattern that lets you check whether print head nozzles are clogged.\n"
              "\n"
              "Load a sheet of A4 or letter size plain paper in the paper source selected \n"
              "by the Paper Feed Switch, and click the Print Check Pattern.");
gchar *s = N_("Start Print Head Alignment");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("Check Setting");
gchar *s = N_("Cancel");
gchar *s = N_("Starting automatically head alignment.\n"
              "\n"
              "Since the alignment involves printing, ready the printer (connect the cable and turn the \n"
              "power on), load one sheet of A4 or letter size plain paper in the sheet feeder and click \n"
              "Print Head Alignment.\n"
              "\n"
              "To carry out manual head alignment, click Cancel.\n"
              "Next, click Custom Settings on the Maintenance tab of the printer driver, check Align \n"
              "heads manually, and click Send. Then try again.\n"
              "\n"
              "To print and check the current setting, click Check Setting.\n"
              "");
gchar *s = N_("Bottom Plate Cleaning");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Executes Bottom Plate Cleaning.\n"
              "\n"
              "1. Remove the paper from the sheet feeder.\n"
              "2. Fold A4 or letter size plain paper in half. Unfold the paper, and load the paper \n"
              "in the sheet feeder with the ridge of the crease facing down. Then click Execute.\n"
              "");
gchar *s = N_("Print Head Alignment");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Execute head alignment. Examine the printed patterns, and enter the \n"
              "pattern number of the pattern with the least amount of streaking in the \n"
              "fields for columns A to K.");
gchar *s = N_("Column A:");
gchar *s = N_("Column B:");
gchar *s = N_("Column C:");
gchar *s = N_("Column D:");
gchar *s = N_("Column E:");
gchar *s = N_("Horizontal Alignment (-3 to +7)     ");
gchar *s = N_("Column F:");
gchar *s = N_("Column G:");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Column I:");
gchar *s = N_("Column J:");
gchar *s = N_("Column K:");
gchar *s = N_("Column H:");
gchar *s = N_("Deep Cleaning");
gchar *s = N_("Execute");
gchar *s = N_("Cancel");
gchar *s = N_("Unclogs nozzles that cannot be cleared by regular cleaning.\n"
              "\n"
              "Deep cleaning consumes much more ink than regular cleaning. Execute Deep \n"
              "Cleaning only if the nozzle condition does not improve after regular cleaning.\n"
              "\n"
              "After the deep cleaning ends, execute Nozzle Check and check whether the \n"
              "print head nozzles have been unclogged.");
