#!/bin/sh
if [ -f /etc/sysconfig/i18n ]; then
  export LANG=`grep LANG /etc/sysconfig/i18n | perl -e '$lang = <>;\
  $lang =~ / *LANG=\"*([\w\-]+\.*[\w\-]*)\"*/; print $1' 2>/dev/null`
fi

args=$@
hostname=`echo $args | perl -e '$sw = <>;  $sw =~ /(^| +)-[hH] *([\S]+)( |$)/;\ print $2' 2>/dev/null`

/usr/local/bin/lgmonip5200 --gui --noparent --display $hostname:0.0
