/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainWindow (void)
{
  GtkWidget *mainWindow;
  GtkWidget *vboxMain;
  GtkWidget *scrolledMain;
  GtkWidget *textMainStatus;
  GtkWidget *labelMainLeverPosition;
  GtkWidget *drawMainCartridge;

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mainWindow), _("title"));

  vboxMain = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxMain);
  gtk_container_add (GTK_CONTAINER (mainWindow), vboxMain);

  scrolledMain = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledMain);
  gtk_box_pack_start (GTK_BOX (vboxMain), scrolledMain, TRUE, TRUE, 10);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledMain), 10);
  GTK_WIDGET_UNSET_FLAGS (scrolledMain, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledMain), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledMain), GTK_SHADOW_IN);

  textMainStatus = gtk_text_view_new ();
  gtk_widget_show (textMainStatus);
  gtk_container_add (GTK_CONTAINER (scrolledMain), textMainStatus);
  gtk_widget_set_size_request (textMainStatus, 280, 280);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textMainStatus), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textMainStatus), GTK_WRAP_WORD);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textMainStatus), FALSE);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textMainStatus)), _("printer status message"), -1);

  labelMainLeverPosition = gtk_label_new ("");
  gtk_widget_show (labelMainLeverPosition);
  gtk_box_pack_start (GTK_BOX (vboxMain), labelMainLeverPosition, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (labelMainLeverPosition), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (labelMainLeverPosition), 10, 3);

  drawMainCartridge = gtk_drawing_area_new ();
  gtk_widget_show (drawMainCartridge);
  gtk_box_pack_start (GTK_BOX (vboxMain), drawMainCartridge, FALSE, TRUE, 0);
  gtk_widget_set_size_request (drawMainCartridge, 50, 90);

  g_signal_connect ((gpointer) mainWindow, "destroy",
                    G_CALLBACK (on_mainWindow_destroy),
                    NULL);
  g_signal_connect ((gpointer) drawMainCartridge, "configure_event",
                    G_CALLBACK (on_drawMainCartridge_configure_event),
                    NULL);
  g_signal_connect ((gpointer) drawMainCartridge, "expose_event",
                    G_CALLBACK (on_drawMainCartridge_expose_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, mainWindow, "mainWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, vboxMain, "vboxMain");
  GLADE_HOOKUP_OBJECT (mainWindow, scrolledMain, "scrolledMain");
  GLADE_HOOKUP_OBJECT (mainWindow, textMainStatus, "textMainStatus");
  GLADE_HOOKUP_OBJECT (mainWindow, labelMainLeverPosition, "labelMainLeverPosition");
  GLADE_HOOKUP_OBJECT (mainWindow, drawMainCartridge, "drawMainCartridge");

  return mainWindow;
}

