#!/bin/sh

if [ -x /sbin/ldconfig ]; then
	/sbin/ldconfig
fi
# remove cnbp* libs
for LIBS in libcnnet libcnbpcnclapicom
do
	if [ -h /usr/lib/${LIBS}${model_num}.so ]; then
		rm -f /usr/lib/${LIBS}${model_num}.so
	fi	
	if [ -h /usr/lib32/${LIBS}${model_num}.so ]; then
		rm -f /usr/lib32/${LIBS}${model_num}.so
	fi	
done
if [ "$1" = 0 ] ; then
	rmdir -p --ignore-fail-on-non-empty /usr/lib/bjlib
fi
