/*
 * Translatable strings file generated by keytext.pl.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("BJF850");
gchar *s = N_("BJF860");
gchar *s = N_("BJF870");
gchar *s = N_("BJF360");
gchar *s = N_("BJS600");
gchar *s = N_("BJS630");
gchar *s = N_("BJS6300");
gchar *s = N_("BJF900");
gchar *s = N_("BJF9000");
gchar *s = N_("BJS500");
gchar *s = N_("BJS300");
gchar *s = N_("PIXUS 550i");
gchar *s = N_("PIXUS 850i");
gchar *s = N_("PIXUS 950i");
gchar *s = N_("i250");
gchar *s = N_("i255");
gchar *s = N_("PIXUS 560i");
gchar *s = N_("PIXUS 860i");
gchar *s = N_("PIXUS 990i");
gchar *s = N_("Color");
gchar *s = N_("Grayscale");
gchar *s = N_("Photo");
gchar *s = N_("Graphic");
gchar *s = N_("Do you want to change the Paper Source setting to %s,\n"
              "which is optimum for the selected Media Type.");
gchar *s = N_("Changing %s to %s is recommended.\n"
              "Click Change to use the new combination, Ignore to use the current\n"
              "combination, or Back to Setup to select a different combination.");
gchar *s = N_("Changing %s setting is recommended.\n"
              "Use the selector below to choose a suitable setting and click Change to use\n"
              "tke new combination. Click Ignore to use the current combination or Back to\n"
              "Setup to select a different combination.");
gchar *s = N_("Move the paper thickness lever %s.");
gchar *s = N_("Media Type");
gchar *s = N_("Paper Size");
gchar *s = N_("Media Type: %s cannot be used\n"
              "with the selected BJ Cartridge.\n"
              "Select the type of media you intend to use.");
gchar *s = N_("Plain Paper");
gchar *s = N_("Transparency");
gchar *s = N_("Back Print Film");
gchar *s = N_("Fabric Sheet");
gchar *s = N_("High Gloss Film");
gchar *s = N_("Japanese Postcard");
gchar *s = N_("Envelope");
gchar *s = N_("Glossy Hagaki");
gchar *s = N_("High Resolution Paper");
gchar *s = N_("T-Shirt Transfer");
gchar *s = N_("Thick Paper");
gchar *s = N_("High Gloss Photo Film");
gchar *s = N_("Glossy Photo Paper");
gchar *s = N_("Glossy Photo Cards");
gchar *s = N_("Photo Paper Pro");
gchar *s = N_("Ink Jet Postcard");
gchar *s = N_("Matte Photo Paper");
gchar *s = N_("Photo Paper Plus Glossy");
gchar *s = N_("Other Paper");
gchar *s = N_("Manual Feed");
gchar *s = N_("Auto Sheet Feeder");
gchar *s = N_("Auto Feeder2");
gchar *s = N_("Standard Cassette");
gchar *s = N_("Option Cassette");
gchar *s = N_("Auto Select");
gchar *s = N_("Consecutive paper feeding");
gchar *s = N_("Tractor Feeder");
gchar *s = N_("Enhanced Black");
gchar *s = N_("A5 148.0 x 210.0 mm");
gchar *s = N_("A5 L 210.0 x 148.0 mm");
gchar *s = N_("A4 210.0 x 297.0 mm");
gchar *s = N_("A4 L 297.0 x 210.0 mm");
gchar *s = N_("A3 297.0 x 420.0 mm");
gchar *s = N_("A3 L 420.0 x 297.0 mm");
gchar *s = N_("A2 420.0 x 594.0 mm");
gchar *s = N_("B5 182.0 x 257.0 mm");
gchar *s = N_("B5 L 257.0 x 182.0 mm");
gchar *s = N_("B4 257.0 x 364.0 mm");
gchar *s = N_("B4 L 364.0 x 257.0 mm");
gchar *s = N_("B3 364.0 x 515.0 mm");
gchar *s = N_("Letter 8.50 x 11.00 in");
gchar *s = N_("Letter L 11.00 x 8.50 in");
gchar *s = N_("Legal 8.50 x 14.00 in");
gchar *s = N_("Legal L 14.00 x 8.50 in");
gchar *s = N_("11 x 17 11.00 x 17.00 in");
gchar *s = N_("17 x 11 17.00 x 11.00 in");
gchar *s = N_("17 x 22 17.00 x 22.00 in");
gchar *s = N_("Postcard 100.0 x 148.0 mm");
gchar *s = N_("Postcard L 148.0 x 100.0 mm");
gchar *s = N_("Comm. Env. #10 9.50 x 4.12 in");
gchar *s = N_("DL Env. 220.0 x 110.0 mm");
gchar *s = N_("13.5 x 17 13.50 x 17.00 in");
gchar *s = N_("Fanfold 8.5 x 11 8.50 x 11.00 in");
gchar *s = N_("Fanfold 9.5 x 11 9.50 x 11.00 in");
gchar *s = N_("Fanfold 10 x 11 10.00 x 11.00 in");
gchar *s = N_("Fanfold 10 x 12 10.00 x 12.00 in");
gchar *s = N_("Fanfold 12 x 8.5 12.00 x 8.50 in");
gchar *s = N_("Fanfold 14.5 x 11 14.50 x 11.00 in");
gchar *s = N_("Fanfold 15 x 11 15.00 x 11.00 in");
gchar *s = N_("Fanfold 15 x 12 15.00 x 12.00 in");
gchar *s = N_("US Fanfold 14.87 x 11.00 in");
gchar *s = N_("Env. #4 235.0 x 105.0 mm");
gchar *s = N_("Env. #6 190.0 x 98.0 mm");
gchar *s = N_("Letter+ 9.0 x 13.3 in");
gchar *s = N_("A4+ 223.5 x 355.6 mm");
gchar *s = N_("A3+ 329.0 x 483.0 mm");
gchar *s = N_("Canon 4 x 6 in");
gchar *s = N_("Custom...");
gchar *s = N_("Comm. Env. #10 4.12 x 9.50 in");
gchar *s = N_("DL Env. 110.0 x 220.0 mm");
gchar *s = N_("Env. #4 105.0 x 235.0 mm");
gchar *s = N_("Env. #6 98.0 x 190.0 mm");
gchar *s = N_("L size 89.0 x 127.0 mm");
gchar *s = N_("2L size 127.0 x 178.0 mm");
gchar *s = N_("4 x 6 in 101.6 x 152.4 mm");
gchar *s = N_("Panorama 89.0 x 254.0 mm");
gchar *s = N_("5 x 7 in 127.0 x 177.8 mm");
gchar *s = N_("Return mail postcard 200.0 x 148.0 mm");
gchar *s = N_("Long Env. #3 120.0 x 235.0 mm");
gchar *s = N_("Long Env. #4 90.0 x 205.0 mm");
gchar *s = N_("FINE");
gchar *s = N_("FINE");
gchar *s = N_("CP");
gchar *s = N_("HQ");
gchar *s = N_("NORMAL");
gchar *s = N_("HS");
gchar *s = N_("ECONOMY");
gchar *s = N_("PHOTO");
gchar *s = N_("PHOTO");
gchar *s = N_("PHOTO");
gchar *s = N_("High Speed");
gchar *s = N_("Average (Speed-biased)");
gchar *s = N_("Average (Quality-biased)");
gchar *s = N_("High Quality");
gchar *s = N_("Top Quality");
gchar *s = N_("Position 1");
gchar *s = N_("Position 2");
gchar *s = N_("Position 3");
gchar *s = N_("Left");
gchar *s = N_("Center");
gchar *s = N_("Right");
gchar *s = N_("Down");
gchar *s = N_("Up");
gchar *s = N_("Down");
gchar *s = N_("Up");
gchar *s = N_("Front");
gchar *s = N_("Back");
gchar *s = N_("Down");
gchar *s = N_("Up");
gchar *s = N_("180x180 dpi");
gchar *s = N_("360x360 dpi");
gchar *s = N_("720x360 dpi");
gchar *s = N_("720x720 dpi");
gchar *s = N_("300x300 dpi");
gchar *s = N_("600x600 dpi");
gchar *s = N_("1200x600 dpi");
gchar *s = N_("Smoothing");
gchar *s = N_("Fine");
gchar *s = N_("Fine(Fast)");
gchar *s = N_("Banner printing");
gchar *s = N_("Color    ");
gchar *s = N_("Black    ");
gchar *s = N_("Photo    ");
gchar *s = N_("Black/Color    ");
gchar *s = N_("Black/Photo    ");
gchar *s = N_("Photo/Color    ");
gchar *s = N_("Fit-to-Page Printing");
gchar *s = N_("Normal-size Printing");
gchar *s = N_("Scaled Printing");
gchar *s = N_("Default");
gchar *s = N_("More bright (Gamma = 1.0)");
gchar *s = N_("Light");
gchar *s = N_("Normal");
gchar *s = N_("Dark");
gchar *s = N_("Auto");
gchar *s = N_("Wide");
gchar *s = N_("Narrow");
gchar *s = N_("You have selected Borderless Printing.\n"
              "The document to be printed slightly extends off the paper.\n"
              "Print quality may deteriorate or the sheet may be stained\n"
              "at the top and bottom depending on the type of the media used.");
gchar *s = N_("Borderless printing is not recommended\n"
              "when %s is selected for Media Type.\n"
              "Select the type of media you intend to use.");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Yes");
gchar *s = N_("No");
gchar *s = N_("Abort");
gchar *s = N_("Ignore");
gchar *s = N_("Enable");
gchar *s = N_("Disable");
gchar *s = N_("5 min");
gchar *s = N_("10 min");
gchar *s = N_("15 min");
gchar *s = N_("30 min");
gchar *s = N_("60 min");
gchar *s = N_("Starting [Print Head Alignment] to compensate for print head installation position error.\n"
              "Execution of this operatin following the replacement of the BJ cartridge for optimum printing is recommended.");
gchar *s = N_("Do not start another operation until current operation is finished.");
gchar *s = N_("Did the pattern print successfully?\n"
              "\n"
              "If nothing was printed, or if the pattern is noticeably faint or patchy, click No and try again.");
gchar *s = N_("Make sure the printer power is on, the cable is connected properly, and the printer is online, then try again.");
gchar *s = N_("Print head alignment is now complete.");
gchar *s = N_("Do not start another operation until current one has finished.");
gchar *s = N_("Start printing nozzle check pattern? Load some paper in the Auto Sheet Feeder to proceed with printing.");
gchar *s = N_("Turn printer off?");
gchar *s = N_("Write settings to printer?");
gchar *s = N_("Cleaning paper feed rollers.\n"
              "\n"
              "You will need the special Cleaning Plate and two sheets of plain paper.\n"
              "First wet the cleaning area of the Cleaning Plate. Wipe away moisture in other areas on the front and back.\n"
              "Place the Cleaning Plate in the Auto Feeder so that the cleaning area is toward you.\n"
              "During cleaning, the paper feed rollers will be activated 20 times. The process will take about a minute.\n"
              "\n"
              "Do you want to start roller cleaning?");
gchar *s = N_("Start cleaning?");
gchar *s = N_("Start print head deep cleaning?");
gchar *s = N_("To remove any moisture left on the paper feed rollers,\n"
              "keep the Cleaning Plate in place and insert the first sheet of plain paper into the Auto Feeder.");
gchar *s = N_("With the Cleaning Plate still in place,\n"
              "insert the second sheet of plain paper into the Auto Feeder to remove any remaining moisture.");
gchar *s = N_("Feed roller cleaning is complete.\n"
              "Remove the Cleaning Plate.");
gchar *s = N_("Starting [Print Head Alignment] to compensate for print head installation position error.\n"
              "Ready the printer (connect the cable and turn the pwoer on), move the printer's thickness lever up,\n"
              "and load a sheet of plain paper in the sheet feeder.\n"
              "\n"
              "Do you want to make any adjustment?");
gchar *s = N_("Bi-directional Alignment(-5 to +5)");
gchar *s = N_("Do you want to clean the paper feed rollers?\n"
              "Load the special cleaning sheet in the sheet feeder to do this.");
gchar *s = N_("Starting Print Head Alignment to compensate for print head installation positioning error.\n"
              "\n"
              "For optimum printing, carry out this operation after replacing a BJ Cartridge.\n"
              "\n"
              "Since alignment involves printing, make sure the printer is ready(cable connected and printer power on),\n"
              "and load a sheet of paper. Both standard and high resolution alignment will be done.\n"
              "\n"
              "Start print head alignment?");
gchar *s = N_("Aligning for high resolution consecutively.\n"
              "\n"
              "Load a new sheet of paper or reuse the same one, and clik OK.\n"
              "The high resolution pattern will be printed.");
gchar *s = N_("Starting Print Head Alignment to compensate for print head installation positioning error.\n"
              "\n"
              "Since alignment involves printing, make sure the printer is ready(cable connected and printer power on),move\n"
              "the printer's thickness lever left, and load a sheet of paper in the sheet feeder. Head alignment patterns\n"
              "will be printed.\n"
              "\n"
              "Start print head alignment?");
gchar *s = N_("Additional head alignmnet patterns will be printed.\n"
              "Load another sheet of paper and click OK.");
gchar *s = N_("Deep cleaning requires a lot of ink. Execute it when doing cleaning several times does not resolve the print head problem.\n"
              "\n"
              "Start print head deep cleaning?");
gchar *s = N_("Execute black print head deep cleaning?");
gchar *s = N_("Execute color print head deep cleaning?");
gchar *s = N_("Starting Print Head Alignment to compensate for print head installation positioning error.\n"
              "\n"
              "Since alignment involves printing, make sure the printer is ready (cable connected and printer power on) \n"
              "and load a sheet of paper in the sheet feeder. Head alignment patterns will be printed.\n"
              "\n"
              "Start print head alignment?");
gchar *s = N_("Print head alignment is complete.\n"
              "To finish the alignment, click Cancel.\n"
              "\n"
              "If streaks appear on the printing side, you can prevent them from appearing by aligning the print head.\n"
              "To proceed to this alignment, insert a sheet of paper into the sheet feeder and click OK.");
gchar *s = N_("Cleaning paper feed rollers.\n"
              "\n"
              "First remove paper from the sheet feeder. Clicking OK will activate paper feed rollers 30 times. \n"
              "This activation will take about one minute and a half. When you set three sheets of plain paper \n"
              "according to the message, paper will be ejected and feed roller cleaning will be completed.\n"
              "\n"
              "Do you want to start feed roller cleaning?\n");
gchar *s = N_("Load three sheets of plain paper in the sheet feeder.\n");
gchar *s = N_("Starting Print Head Alignment to compensate for print head installation positioning error.\n"
              "\n"
              "Since alignment involves printing, make sure the printer is ready (cable connected and printer power on) and \n"
              "load a sheet of paper in the sheet feeder. Head alignment patterns will be printed.\n"
              "\n"
              "Start print head alignment?\n");
gchar *s = N_("Feed roller cleaning is complete.");
gchar *s = N_("All Colors");
gchar *s = N_("Black   3eBK");
gchar *s = N_("Color   6C, 6M, 6Y");
gchar *s = N_("Color   6C, 6M, 6Y, 6BK");
gchar *s = N_("Group 1   6BK, 6R, 6PC, 6PM");
gchar *s = N_("Group 2   6C, 6M, 6Y");
gchar *s = N_("Execute print head deep cleaning for Group 1?\n");
gchar *s = N_("Execute print head deep cleaning for Group 2?\n");
gchar *s = N_("Executes print head cleaning.\n"
              "\n"
              "Select print head for cleaning. The ink group can be identified from \n"
              "the nozzle check pattern.\n");
gchar *s = N_("Deep cleaning requires a lot of ink.Execute deep cleaning if the print head problem \n"
              "is not resolved after several regular cleanings.\n"
              "\n"
              "Select the print head for deep cleaning. The ink group can be identified from the nozzle check pattern.\n");
gchar *s = N_("Do you want to carry out automatic head alignment?\n"
              "\n"
              "Ready the printer (connect the cable and turn the power on) and load a sheet of paper normally \n"
              "in the sheet feeder, since alignment entails printing.\n"
              "\n"
              "To carry out manual head alignment, click Cancel, check Align heads manually in the Custom \n"
              "Settings dialog box, and click Send.\n");
gchar *s = N_("Do you want to carry out simple head alignment?\n"
              "\n"
              "Ready the printer (connect the cable and turn the power on), load two sheets of plain paper \n"
              "in the sheet feeder and click OK.\n"
              "Once this operation starts, it cannot be stopped until it is complete.\n"
              "To carry out manual head alignment, click Cancel, check Align heads manually in the Custom \n"
              "Settings dialog box, and click Send. Then try again.\n");
gchar *s = N_("The rest of the alignment process will be executed. \n"
              "Check that the paper is loaded and click OK.\n"
              "\n"
              "The subsequent process will be executed automatically.\n");
