#!/usr/bin/perl

print "\/\*\n";
print " * Translatable strings file generated by keytext.pl.\n";
print " * Add this file to your project's POTFILES.in.\n";
print " * DO NOT compile it as part of your application.\n";
print " \*\/\n\n";

while(<>) {
	$keytext = $keytext.$_;
}

$keytext =~ /<(KeyTextList)>([\w\W]*?)<\/\1>/i;
$itemlist = $2;

while ($itemlist =~ /<(Item)([\w\W]*?)>([\w\W]*?)<\/\1>/ig) {
	$item = $2;
	$text = $3;

	$text =~ s/\"/\\\"/g;

	$item =~ /key *= *\" *([\w]*?) *\"/i;
	$key = $1;

	if ( length $text > 0 ){
		print "gchar \*s = N_\(\"";
		$count = 0;
		
		while ( $text =~ /(^.*)/mg ){
			$line = $1;
			$next = $';

			if ( $count != 0 ) {
				print "\"\n";
				print "              \"";
			}
			
			if ( ($line eq "") && ($next eq "") ){
				print "parse error.\n";
			}

			if ( $line ne "" ){
				print $line;
			}

			if ( $next =~ /^\n/ ){
				print "\\n";
			}

			$count++;
		}

		print "\"\)\;\n";
	}
}

