/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ui_window (void);
GtkWidget* create_regi_common_type001_dialog (void);
GtkWidget* create_regi_common_type002_dialog (void);
GtkWidget* create_setconfig_type001_dialog (void);
GtkWidget* create_setconfig_type003_dialog (void);
GtkWidget* create_cleaning_type001_dialog (void);
GtkWidget* create_nozzle_check_type001_dialog (void);
GtkWidget* create_nozzle_check_type002_dialog (void);
