/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("title");
gchar *s = N_("printer status message");
gchar *s = N_("Cartridge Type:");
gchar *s = N_("Continue");
gchar *s = N_("Cancel Printing");
