/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ui_window (void);
GtkWidget* create_user_size_dialog (void);
GtkWidget* create_quality_dialog (void);
GtkWidget* create_color_dialog (void);
GtkWidget* create_version_dialog (void);
GtkWidget* create_mediasize_illegal_dialog (void);
GtkWidget* create_mediasize_recommend_dialog (void);
GtkWidget* create_mediatype_dialog (void);
GtkWidget* create_mediaborder_dialog (void);
GtkWidget* create_mediasize_illegal_select_dialog (void);
GtkWidget* create_color_dialog2 (void);
GtkWidget* create_regi_common_type001_dialog (void);
GtkWidget* create_regi_common_type002_dialog (void);
GtkWidget* create_setconfig_type001_dialog (void);
GtkWidget* create_setconfig_type003_dialog (void);
GtkWidget* create_cleaning_type001_dialog (void);
GtkWidget* create_nozzle_check_type001_dialog (void);
GtkWidget* create_nozzle_check_type002_dialog (void);
