/*
 * Translatable strings file generated by keytext.pl.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("BJF850");
gchar *s = N_("BJF860");
gchar *s = N_("BJF870");
gchar *s = N_("BJF360");
gchar *s = N_("BJS600");
gchar *s = N_("BJS630");
gchar *s = N_("BJS6300");
gchar *s = N_("BJF900");
gchar *s = N_("BJF9000");
gchar *s = N_("BJS500");
gchar *s = N_("BJS300");
gchar *s = N_("PIXUS 550i");
gchar *s = N_("PIXUS 850i");
gchar *s = N_("PIXUS 950i");
gchar *s = N_("i250");
gchar *s = N_("i255");
gchar *s = N_("PIXUS 560i");
gchar *s = N_("PIXUS 860i");
gchar *s = N_("PIXUS 990i");
gchar *s = N_("PIXUS iP3100");
gchar *s = N_("PIXUS iP4100");
gchar *s = N_("PIXUS iP8600");
gchar *s = N_("PIXMA iP1000");
gchar *s = N_("PIXMA iP1500");
gchar *s = N_("iP2200");
gchar *s = N_("iP4200");
gchar *s = N_("iP6600D");
gchar *s = N_("iP7500");
gchar *s = N_("MP500");
gchar *s = N_("Color");
gchar *s = N_("Grayscale");
gchar *s = N_("Photo");
gchar *s = N_("Graphic");
gchar *s = N_("Do you want to change the Paper Source setting to %s,\n"
              "which is optimum for the selected Media Type.");
gchar *s = N_("Changing %s to %s is recommended.");
gchar *s = N_("Click Change to use the new combination, Ignore to use the current\n"
              "combination, or Back to Setup to select a different combination.");
gchar *s = N_("Changing %s setting is recommended.");
gchar *s = N_("Use the selector below to choose a suitable setting and click Change to use\n"
              "the new combination. Click Ignore to use the current combination or Back to\n"
              "Setup to select a different combination.");
gchar *s = N_("Changing %s setting is recommended.  ");
gchar *s = N_("Use the selector below to choose a suitable setting and click Change to use\n"
              "the new combination. Click Back to Setup to select a different combination.");
gchar *s = N_("Move the paper thickness lever %s.");
gchar *s = N_("Media Type");
gchar *s = N_("Page Size");
gchar *s = N_("Media Type: %s cannot be used\n"
              "with the selected BJ Cartridge.\n"
              "Select the type of media you intend to use.");
gchar *s = N_("Plain Paper");
gchar *s = N_("Transparencies");
gchar *s = N_("Back Print Film");
gchar *s = N_("Fabric Sheet");
gchar *s = N_("High Gloss Film");
gchar *s = N_("Hagaki");
gchar *s = N_("Envelope");
gchar *s = N_("Glossy Postcard");
gchar *s = N_("High Resolution Paper");
gchar *s = N_("T-Shirt Transfers");
gchar *s = N_("Thick Paper");
gchar *s = N_("High Gloss Photo Film");
gchar *s = N_("Glossy Photo Paper");
gchar *s = N_("Glossy Photo Cards");
gchar *s = N_("Photo Paper Pro");
gchar *s = N_("Ink Jet Hagaki");
gchar *s = N_("Matte Photo Paper");
gchar *s = N_("Photo Paper Plus Glossy");
gchar *s = N_("Other Paper");
gchar *s = N_("Other Photo Paper");
gchar *s = N_("Photo Paper Plus Double Sided");
gchar *s = N_("Fine Art Photo Rag");
gchar *s = N_("Other Fine Art Paper");
gchar *s = N_("Manual Feed");
gchar *s = N_("Auto Sheet Feeder");
gchar *s = N_("Auto Feeder2");
gchar *s = N_("Standard Cassette");
gchar *s = N_("Optional Cassette");
gchar *s = N_("Auto Select");
gchar *s = N_("Consecutive paper feeding");
gchar *s = N_("Tractor Feeder");
gchar *s = N_("Cassette");
gchar *s = N_("Paper Feed Switch");
gchar *s = N_("Enhanced Black");
gchar *s = N_("A5 148.0 x 210.0 mm");
gchar *s = N_("A5 L 210.0 x 148.0 mm");
gchar *s = N_("A4 210.0 x 297.0 mm");
gchar *s = N_("A4 L 297.0 x 210.0 mm");
gchar *s = N_("A3 297.0 x 420.0 mm");
gchar *s = N_("A3 L 420.0 x 297.0 mm");
gchar *s = N_("A2 420.0 x 594.0 mm");
gchar *s = N_("B5 182.0 x 257.0 mm");
gchar *s = N_("B5 L 257.0 x 182.0 mm");
gchar *s = N_("B4 257.0 x 364.0 mm");
gchar *s = N_("B4 L 364.0 x 257.0 mm");
gchar *s = N_("B3 364.0 x 515.0 mm");
gchar *s = N_("Letter 8.50x11.00in 215.9x279.4mm");
gchar *s = N_("Letter L 11.00x8.50in 279.4x215.9mm");
gchar *s = N_("Legal 8.50x14.00in 215.9x355.6mm");
gchar *s = N_("Legal L 14.00x8.50in 355.6x215.9mm");
gchar *s = N_("11x17in 279.4x431.8mm");
gchar *s = N_("17x11in 431.8x279.4mm");
gchar *s = N_("17x22in 431.8x558.8mm");
gchar *s = N_("Hagaki 100x148mm");
gchar *s = N_("Hagaki L 148x100mm");
gchar *s = N_("Comm. Env. #10 9.50x4.12in 241.3x104.6mm");
gchar *s = N_("DL Env. 220.0 x 110.0 mm");
gchar *s = N_("13.5x17in 342.9x431.8mm");
gchar *s = N_("Fanfold 8.5 x 11 8.50 x 11.00 in");
gchar *s = N_("Fanfold 9.5 x 11 9.50 x 11.00 in");
gchar *s = N_("Fanfold 10 x 11 10.00 x 11.00 in");
gchar *s = N_("Fanfold 10 x 12 10.00 x 12.00 in");
gchar *s = N_("Fanfold 12 x 8.5 12.00 x 8.50 in");
gchar *s = N_("Fanfold 14.5 x 11 14.50 x 11.00 in");
gchar *s = N_("Fanfold 15 x 11 15.00 x 11.00 in");
gchar *s = N_("Fanfold 15 x 12 15.00 x 12.00 in");
gchar *s = N_("US Fanfold 14.87 x 11.00 in");
gchar *s = N_("Youkei 4 235x105.5mm");
gchar *s = N_("Youkei 6 190x98mm");
gchar *s = N_("Letter+ 9.00x13.30in 228.6x337.8mm");
gchar *s = N_("A4+ 223.5 x 355.6 mm");
gchar *s = N_("A3+ 13x19in 329.0x483.0mm");
gchar *s = N_("Canon 4x6in 101.6x152.4mm");
gchar *s = N_("Custom...");
gchar *s = N_("Comm. Env. #10 4.12x9.50in 104.6x241.3mm");
gchar *s = N_("DL Env. 110.0 x 220.0 mm");
gchar *s = N_("Youkei 4 105.5x235mm");
gchar *s = N_("Youkei 6 98x190mm");
gchar *s = N_("L 89x127mm");
gchar *s = N_("2L 127x178mm");
gchar *s = N_("4x6in 101.6x152.4mm");
gchar *s = N_("P 89x254mm");
gchar *s = N_("5x7in 127.0x177.8mm");
gchar *s = N_("Hagaki 2 200x148mm");
gchar *s = N_("Choukei 3 120x235mm");
gchar *s = N_("Choukei 4 90x205mm");
gchar *s = N_("Card 2.16x3.58in 55x91mm");
gchar *s = N_("Credit Card 2.13x3.39in 54x86mm");
gchar *s = N_("Fine Art A4 210.0 x 297.0 mm");
gchar *s = N_("4x8in 101.6x203.2mm");
gchar *s = N_("8x10in 203.2x254.0mm");
gchar *s = N_("FINE");
gchar *s = N_("FINE");
gchar *s = N_("CP");
gchar *s = N_("HQ");
gchar *s = N_("NORMAL");
gchar *s = N_("HS");
gchar *s = N_("ECONOMY");
gchar *s = N_("PHOTO");
gchar *s = N_("PHOTO");
gchar *s = N_("PHOTO");
gchar *s = N_("High Speed");
gchar *s = N_("Average (Speed-biased)");
gchar *s = N_("Average (Quality-biased)");
gchar *s = N_("High Quality");
gchar *s = N_("Top Quality");
gchar *s = N_("Position 1");
gchar *s = N_("Position 2");
gchar *s = N_("Position 3");
gchar *s = N_("Left");
gchar *s = N_("Center");
gchar *s = N_("Right");
gchar *s = N_("Down");
gchar *s = N_("Up");
gchar *s = N_("Down");
gchar *s = N_("Up");
gchar *s = N_("Front");
gchar *s = N_("Back");
gchar *s = N_("Down");
gchar *s = N_("Up");
gchar *s = N_("180x180 dpi");
gchar *s = N_("360x360 dpi");
gchar *s = N_("720x360 dpi");
gchar *s = N_("720x720 dpi");
gchar *s = N_("300x300 dpi");
gchar *s = N_("600x600 dpi");
gchar *s = N_("1200x600 dpi");
gchar *s = N_("Smoothing");
gchar *s = N_("Fine");
gchar *s = N_("Fine(Fast)");
gchar *s = N_("Banner Printing");
gchar *s = N_("Color    ");
gchar *s = N_("Black    ");
gchar *s = N_("Photo    ");
gchar *s = N_("Black/Color    ");
gchar *s = N_("Black/Photo    ");
gchar *s = N_("Photo/Color    ");
gchar *s = N_("Fit-to-Page Printing");
gchar *s = N_("Normal-size Printing");
gchar *s = N_("Scaled Printing");
gchar *s = N_("Default");
gchar *s = N_("More bright (Gamma = 1.0)");
gchar *s = N_("Light");
gchar *s = N_("Normal");
gchar *s = N_("Dark");
gchar *s = N_("Auto");
gchar *s = N_("Wide");
gchar *s = N_("Narrow");
gchar *s = N_("You have selected Borderless Printing.\n"
              "The document to be printed slightly extends off the paper.\n"
              "Print quality may deteriorate or the sheet may be stained\n"
              "at the top and bottom depending on the type of the media used.");
gchar *s = N_("Borderless printing is not recommended\n"
              "when %s is selected for Media Type.\n"
              "Select the type of media you intend to use.");
gchar *s = N_("The document to be printed slightly extends off the paper.\n"
              "Print quality may deteriorate or the sheet may be stained\n"
              "at the top and bottom depending on the type of the media used.");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Yes");
gchar *s = N_("No");
gchar *s = N_("Abort");
gchar *s = N_("Ignore");
gchar *s = N_("Enable");
gchar *s = N_("Disable");
gchar *s = N_("5 minutes");
gchar *s = N_("10 minutes");
gchar *s = N_("15 minutes");
gchar *s = N_("30 minutes");
gchar *s = N_("60 minutes");
gchar *s = N_("Starting Print Head Alignment to compensate for print head installation positioning error.\n"
              "\n"
              "Alignment entails printing, so do the following.\n"
              "Ready the printer (connect the cable and turn the power on), move the printer's paper thickness lever up, and load a sheet of high resolution paper in the sheet feeder.\n"
              "\n"
              "Do you want to make any adjustment?");
gchar *s = N_("Do not start another operation until current one has finished.");
gchar *s = N_("Were the patterns printed normally?\n"
              "\n"
              "If no patterns were printed or if the printout is noticeably blurred, click No and start again from the beginning.");
gchar *s = N_("Make sure the printer power is on, the cable is connected properly, and the printer is online, then try again.");
gchar *s = N_("Print head alignment is now complete.");
gchar *s = N_("Do not start another operation until current one has finished.");
gchar *s = N_("Start printing nozzle check pattern? Load some paper in the sheet feeder to proceed with printing.");
gchar *s = N_("Turn printer off?");
gchar *s = N_("Write settings to printer?");
gchar *s = N_("Cleaning paper feed rollers.\n"
              "\n"
              "You will need the special Cleaning Plate and two sheets of plain paper.\n"
              "First wet the cleaning area of the Cleaning Plate. Wipe away any moisture in other areas on the front and back.\n"
              "Place the Cleaning Plate in the sheet feeder so that the cleaning area is toward you.\n"
              "During cleaning, the paper feed rollers will be activated 20 times. The process will take about a minute.\n"
              "\n"
              "Do you want to start roller cleaning?");
gchar *s = N_("Start cleaning?");
gchar *s = N_("Start print head deep cleaning?");
gchar *s = N_("To remove any moisture left on the paper feed rollers,\n"
              "keep the Cleaning Plate in place and insert the first sheet of plain paper into the sheet feeder.");
gchar *s = N_("With the Cleaning Plate still in place,\n"
              "insert the second sheet of plain paper into the sheet feeder to remove any remaining moisture.");
gchar *s = N_("Feed roller cleaning is complete.\n"
              "Remove the Cleaning Plate.");
gchar *s = N_("Starting Print Head Alignment to compensate for print head installation positioning error.\n"
              "\n"
              "Alignment entails printing, so do the following.\n"
              "Ready the printer (connect the cable and turn the power on), move the printer's paper thickness lever up, and load a sheet of plain paper in the sheet feeder.\n"
              "\n"
              "Do you want to make any adjustment?");
gchar *s = N_("Bi-directional Alignment (-5 to +5)");
gchar *s = N_("Do you want to clean the paper feed rollers?\n"
              "Load the special cleaning sheet in the sheet feeder to do this.");
gchar *s = N_("Starting Print Head Alignment to compensate for print head installation positioning error.\n"
              "\n"
              "For optimum printing, carry out this operation after replacing a BJ Cartridge.\n"
              "\n"
              "Since alignment involves printing, make sure the printer is ready (cable connected and printer power on),\n"
              "and load a sheet of paper in the sheet feeder. Both standard and high resolution alignment will be done.\n"
              "\n"
              "Start print head alignment?");
gchar *s = N_("Aligning for high resolution consecutively.\n"
              "\n"
              "Load a new sheet of paper or reuse the same one, and click OK.\n"
              "The high resolution pattern will be printed.");
gchar *s = N_("Starting Print Head Alignment to compensate for print head installation positioning error.\n"
              "\n"
              "Since alignment involves printing, make sure the printer is ready (cable connected and printer power on), move\n"
              "the printer's paper thickness lever left, and load a sheet of paper in the sheet feeder. Head alignment patterns\n"
              "will be printed.\n"
              "\n"
              "Start print head alignment?");
gchar *s = N_("Additional head alignment patterns will be printed.\n"
              "\n"
              "Load another sheet of paper and click OK.");
gchar *s = N_("Deep cleaning requires a lot of ink. Execute it when doing cleaning several times does not resolve the print head problem.\n"
              "\n"
              "Start print head deep cleaning?");
gchar *s = N_("Execute black print head deep cleaning?");
gchar *s = N_("Execute color print head deep cleaning?");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, ready the printer (connect the cable and turn the power on), \n"
              "load a sheet of plain paper in the sheet feeder. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click OK.");
gchar *s = N_("Print head alignment is complete.\n"
              "To finish the alignment, click Cancel.\n"
              "\n"
              "If streaks appear on the printing side, you can prevent them from appearing by aligning the print head.\n"
              "To proceed to this alignment, insert a sheet of paper into the sheet feeder and click OK.");
gchar *s = N_("Cleaning paper feed rollers.\n"
              "\n"
              "First remove paper from the sheet feeder. Clicking OK will activate paper feed rollers 30 times. \n"
              "This activation will take about one minute and a half. When you set three sheets of plain paper \n"
              "according to the message, paper will be ejected and feed roller cleaning will be completed.\n"
              "\n"
              "Do you want to start feed roller cleaning?");
gchar *s = N_("Load three sheets of plain paper in the sheet feeder.\n");
gchar *s = N_("Feed roller cleaning is complete.");
gchar *s = N_("All Colors");
gchar *s = N_("Black   3eBK");
gchar *s = N_("Black   PGBK");
gchar *s = N_("Color   6C, 6M, 6Y");
gchar *s = N_("Color   6C, 6M, 6Y, 6BK");
gchar *s = N_("Color   7C, 7M, 7Y");
gchar *s = N_("Color   7C, 7M, 7Y, 7BK");
gchar *s = N_("Color   C, M, Y, BK");
gchar *s = N_("Color   C, M, Y, PC, PM, BK");
gchar *s = N_("Group 1   6BK, 6R, 6PC, 6PM");
gchar *s = N_("Group 1   7BK, 7R, 7G, 7PC, 7PM");
gchar *s = N_("Group 2   6C, 6M, 6Y");
gchar *s = N_("Group 2   7C, 7M, 7Y");
gchar *s = N_("Execute print head deep cleaning for Group 1?\n");
gchar *s = N_("Execute print head deep cleaning for Group 2?\n");
gchar *s = N_("Executes print head cleaning.\n"
              "\n"
              "Select print head for cleaning. The ink group can be identified from \n"
              "the nozzle check pattern.\n");
gchar *s = N_("Deep cleaning requires a lot of ink. Execute deep cleaning if the print head problem \n"
              "is not resolved after several regular cleanings.\n"
              "\n"
              "Select the print head for deep cleaning. The ink group can be identified from the nozzle check pattern.\n");
gchar *s = N_("Starting automatically head alignment.\n"
              "\n"
              "Ready the printer (connect the cable and turn the power on) and load one sheet of A4 or letter size plain paper in the sheet feeder, since alignment involves printing.\n"
              "\n"
              "To carry out manual head alignment, click Cancel.\n"
              "Next, click Custom Settings on the Maintenance tab of the printer driver, check Align heads manually, and click Send.");
gchar *s = N_("Starting simple head alignment.\n"
              "\n"
              "Since the alignment involves printing, ready the printer (connect the cable and turn the power on), load two sheets of A4 or letter size plain paper in the sheet feeder and click OK.\n"
              "Once this operation starts, it cannot be stopped until it is complete.\n"
              "To carry out manual head alignment, click Cancel.\n"
              "Next, click Custom Settings on the Maintenance tab of the printer driver,  check Align heads manually, and click Send. Then try again.");
gchar *s = N_("The rest of the alignment process will be executed. \n"
              "Check that the paper is loaded and click OK.\n"
              "\n"
              "The subsequent process will be executed automatically.\n");
gchar *s = N_("Do not start another operation until the cleaning has finished.\n"
              "\n"
              "After the cleaning ends, execute Nozzle Check and check whether the print head nozzles have been unclogged.\n");
gchar *s = N_("Cleans clogged print head nozzles.\n"
              "\n"
              "Select the target ink group for cleaning. If you are not sure of the ink group \n"
              "for cleaning, execute Nozzle Check.\n");
gchar *s = N_("Unclogs nozzles that cannot be cleared by regular cleaning.\n"
              "\n"
              "Select the target ink group for deep cleaning. If you are not sure of the ink \n"
              "group for deep cleaning, execute Nozzle Check.\n");
gchar *s = N_("Ink Group:");
gchar *s = N_("Deep cleaning consumes much more ink than regular cleaning. Execute Deep \n"
              "Cleaning only if the nozzle condition does not improve after regular cleaning.\n"
              "\n"
              "After the deep cleaning ends, execute Nozzle Check and check whether the \n"
              "print head nozzles have been unclogged.\n");
gchar *s = N_("Cleaning consumes ink.");
gchar *s = N_("Load a sheet of A4 or letter size paper in the paper source selected by the Paper Feed Switch and click OK.\n");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, ready the printer (connect the cable and turn the \n"
              "power on), load a sheet of A4 or letter size plain paper in the paper source selected by \n"
              "the Paper Feed Switch. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Check Setting.\n"
              "\n");
gchar *s = N_("Prints pattern that lets you check whether print head nozzles are clogged.\n"
              "\n"
              "Load a sheet of A4 or letter size plain paper in the sheet feeder, and click \n"
              "the Print Check Pattern.\n");
gchar *s = N_("\n"
              "If the printed pattern resembles this pattern, the \n"
              "print head nozzles may be clogged.\n"
              "Click Cleaning.\n"
              "\n"
              "If the printed pattern does not improve even \n"
              "after Cleaning is executed two times, \n"
              "execute Deep Cleaning.\n");
gchar *s = N_("\n"
              "Print head alignment is complete.\n"
              "To finish the alignment, click Cancel.\n"
              "\n"
              "If streaks appear on the printing side, you can prevent them from appearing by aligning \n"
              "the print head.\n"
              "To proceed to this alignment, load a sheet of paper into the paper source selected by \n"
              "the Paper Feed Switch and click OK.\n");
gchar *s = N_("\n"
              "Load a sheet of A4 or letter size paper in the sheet feeder and click OK.\n");
gchar *s = N_("\n"
              "The next step is to print an alignment pattern for plain paper printing.\n"
              "\n"
              "Load a sheet of A4 or letter size plain paper in the paper source selected by the Paper Feed Switch, click OK.\n");
gchar *s = N_("Starting automatic head alignment.\n"
              "\n"
              "Since the alignment involves printing, ready the printer (connect the cable and turn the \n"
              "power on), load one sheet of A4 or letter size plain paper in the sheet feeder and click \n"
              "Print Head Alignment. \n"
              "\n"
              "To carry out manual head alignment, click Cancel.\n"
              "Next, click Custom Settings on the Maintenance tab of the printer driver, check Align \n"
              "heads manually, and click Send. Then try again.\n"
              "\n"
              "To print and check the current setting, click Check Setting.\n");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, ready the printer (connect the cable and turn the \n"
              "power on), load a sheet of A4 or letter size plain paper in the paper source selected by \n"
              "the Paper Feed Switch. The printer will first print an alignment pattern for photo paper printing.\n"
              "\n"
              "To align the print head position, click Print Head Alignment.\n"
              "\n"
              "To print and check the current setting, click Check Setting.\n");
gchar *s = N_("Starting print head alignment.\n"
              "\n"
              "Since the alignment involves printing, ready the printer (connect the cable and turn the \n"
              "power on), move the printer's paper thickness lever left, and load a sheet of A4 or \n"
              "letter size plain paper in the sheet feeder. The printer will print an alignment pattern.\n"
              "\n"
              "To align the print head position, click OK.\n");
gchar *s = N_("Prints pattern that lets you check whether print head nozzles are clogged.\n"
              "\n"
              "Ready the printer (connect the cable and turn the power on), move the printer's\n"
              "paper thickness lever left, load a sheet of A4 or letter size plain paper in the\n"
              "sheet feeder, and click the Print Check Pattern.\n");
gchar *s = N_("Color Only");
gchar *s = N_("Black Only");
gchar *s = N_("Both Black and Color");
gchar *s = N_("Prints using only color cartridge instead of\n"
              "black cartridge.");
gchar *s = N_("Prints using only black cartridge instead of\n"
              "color cartridge only when Plain Paper is\n"
              "selected for the Media Type on the Main Tab.");
gchar *s = N_("Prints using both black and color cartridges.");
