#if HAVE_CANON_ADDON
//#if (HAVE_CANON_ADDON = true)
//#endif

  UIConstraints "*InputSlot front *PageSize Legal"
  UIConstraints "*InputSlot front *PageSize A5"
  UIConstraints "*InputSlot front *PageSize 4X6"
  UIConstraints "*InputSlot front *PageSize 4X8"
  UIConstraints "*InputSlot front *PageSize 5X7"
  UIConstraints "*InputSlot front *PageSize 8X10"
  UIConstraints "*InputSlot front *PageSize l"
  UIConstraints "*InputSlot front *PageSize 2l"
  UIConstraints "*InputSlot front *PageSize postcard"
  UIConstraints "*InputSlot front *PageSize postdbl"
  UIConstraints "*InputSlot front *PageSize envelop10p"
  UIConstraints "*InputSlot front *PageSize envelopdlp"
  UIConstraints "*InputSlot front *PageSize envj4p"
  UIConstraints "*InputSlot front *PageSize envj6p"
  UIConstraints "*InputSlot front *PageSize creditcard"
  UIConstraints "*InputSlot front *PageSize businesscard"
  UIConstraints "*InputSlot front *PageSize wide"
  UIConstraints "*InputSlot switch *PageSize Legal"
  UIConstraints "*InputSlot switch *PageSize creditcard"
  UIConstraints "*InputSlot switch *PageSize businesscard"
  UIConstraints "*InputSlot cassette *PageSize Legal"
  UIConstraints "*InputSlot cassette *PageSize 4X6"
  UIConstraints "*InputSlot cassette *PageSize 4X6.bl"
  UIConstraints "*InputSlot cassette *PageSize 4X8"
  UIConstraints "*InputSlot cassette *PageSize 4X8.bl"
  UIConstraints "*InputSlot cassette *PageSize 5X7"
  UIConstraints "*InputSlot cassette *PageSize 5X7.bl"
  UIConstraints "*InputSlot cassette *PageSize 8X10"
  UIConstraints "*InputSlot cassette *PageSize 8X10.bl"
  UIConstraints "*InputSlot cassette *PageSize l"
  UIConstraints "*InputSlot cassette *PageSize l.bl"
  UIConstraints "*InputSlot cassette *PageSize 2l"
  UIConstraints "*InputSlot cassette *PageSize 2l.bl"
  UIConstraints "*InputSlot cassette *PageSize postcard"
  UIConstraints "*InputSlot cassette *PageSize postcard.bl"
  UIConstraints "*InputSlot cassette *PageSize postdbl"
  UIConstraints "*InputSlot cassette *PageSize envelop10p"
  UIConstraints "*InputSlot cassette *PageSize envelopdlp"
  UIConstraints "*InputSlot cassette *PageSize envj4p"
  UIConstraints "*InputSlot cassette *PageSize envj6p"
  UIConstraints "*InputSlot cassette *PageSize creditcard"
  UIConstraints "*InputSlot cassette *PageSize creditcard.bl"
  UIConstraints "*InputSlot cassette *PageSize businesscard"
  UIConstraints "*InputSlot cassette *PageSize businesscard.bl"
  UIConstraints "*InputSlot cassette *PageSize wide"
  UIConstraints "*InputSlot cassette *PageSize wide.bl"
  UIConstraints "*InputSlot cassette *PageSize fineartletter"
  UIConstraints "*InputSlot cassette *PageSize finearta4"
  UIConstraints "*InputSlot continuous *PageSize Legal"
  UIConstraints "*InputSlot continuous *PageSize 4X6"
  UIConstraints "*InputSlot continuous *PageSize 4X6.bl"
  UIConstraints "*InputSlot continuous *PageSize 4X8"
  UIConstraints "*InputSlot continuous *PageSize 4X8.bl"
  UIConstraints "*InputSlot continuous *PageSize 5X7"
  UIConstraints "*InputSlot continuous *PageSize 5X7.bl"
  UIConstraints "*InputSlot continuous *PageSize 8X10"
  UIConstraints "*InputSlot continuous *PageSize 8X10.bl"
  UIConstraints "*InputSlot continuous *PageSize l"
  UIConstraints "*InputSlot continuous *PageSize l.bl"
  UIConstraints "*InputSlot continuous *PageSize 2l"
  UIConstraints "*InputSlot continuous *PageSize 2l.bl"
  UIConstraints "*InputSlot continuous *PageSize postcard"
  UIConstraints "*InputSlot continuous *PageSize postcard.bl"
  UIConstraints "*InputSlot continuous *PageSize postdbl"
  UIConstraints "*InputSlot continuous *PageSize envelop10p"
  UIConstraints "*InputSlot continuous *PageSize envelopdlp"
  UIConstraints "*InputSlot continuous *PageSize envj4p"
  UIConstraints "*InputSlot continuous *PageSize envj6p"
  UIConstraints "*InputSlot continuous *PageSize businesscard"
  UIConstraints "*InputSlot continuous *PageSize businesscard.bl"
  UIConstraints "*InputSlot continuous *PageSize wide"
  UIConstraints "*InputSlot continuous *PageSize wide.bl"
  UIConstraints "*InputSlot continuous *PageSize fineartletter"
  UIConstraints "*InputSlot continuous *PageSize finearta4"

  UIConstraints "*Duplex  *MediaType prophoto"
  UIConstraints "*Duplex  *MediaType superphoto"
  UIConstraints "*Duplex  *MediaType glossygold"
  UIConstraints "*Duplex  *MediaType prophoto2"
  UIConstraints "*Duplex  *MediaType proplatinum"
  UIConstraints "*Duplex  *MediaType luster"
  UIConstraints "*Duplex  *MediaType semigloss"
  UIConstraints "*Duplex  *MediaType glossypaper"
  UIConstraints "*Duplex  *MediaType matte"
  UIConstraints "*Duplex  *MediaType otherfineart"
  UIConstraints "*Duplex  *MediaType envelope"
  UIConstraints "*Duplex  *MediaType ijpostcard"
  UIConstraints "*Duplex  *MediaType glossypost"
  UIConstraints "*Duplex  *MediaType prophotopost"
  UIConstraints "*Duplex  *MediaType fineartphotorag"
  UIConstraints "*Duplex  *MediaType highres"
  UIConstraints "*Duplex  *MediaType tshirt"
  UIConstraints "*Duplex  *MediaType postcardaddress"
  UIConstraints "*Duplex  *MediaType postcard"
  UIConstraints "*Duplex  *MediaType otherphoto"
  UIConstraints "*Duplex  *PageSize Letter.bl"
  UIConstraints "*Duplex  *PageSize Legal"
  UIConstraints "*Duplex  *PageSize A5"
  UIConstraints "*Duplex  *PageSize A4.bl"
  UIConstraints "*Duplex  *PageSize B5"
  UIConstraints "*Duplex  *PageSize 4X6"
  UIConstraints "*Duplex  *PageSize 4X6.bl"
  UIConstraints "*Duplex  *PageSize 4X8"
  UIConstraints "*Duplex  *PageSize 4X8.bl"
  UIConstraints "*Duplex  *PageSize 5X7"
  UIConstraints "*Duplex  *PageSize 5X7.bl"
  UIConstraints "*Duplex  *PageSize 8X10"
  UIConstraints "*Duplex  *PageSize 8X10.bl"
  UIConstraints "*Duplex  *PageSize l"
  UIConstraints "*Duplex  *PageSize l.bl"
  UIConstraints "*Duplex  *PageSize 2l"
  UIConstraints "*Duplex  *PageSize 2l.bl"
  UIConstraints "*Duplex  *PageSize letterfineart35"
  UIConstraints "*Duplex  *PageSize a4fineart35"
  UIConstraints "*Duplex  *PageSize postcard"
  UIConstraints "*Duplex  *PageSize postcard.bl"
  UIConstraints "*Duplex  *PageSize postdbl"
  UIConstraints "*Duplex  *PageSize envelop10p"
  UIConstraints "*Duplex  *PageSize envelopdlp"
  UIConstraints "*Duplex  *PageSize envj4p"
  UIConstraints "*Duplex  *PageSize envj6p"
  UIConstraints "*Duplex  *PageSize creditcard"
  UIConstraints "*Duplex  *PageSize creditcard.bl"
  UIConstraints "*Duplex  *PageSize businesscard"
  UIConstraints "*Duplex  *PageSize businesscard.bl"
  UIConstraints "*Duplex  *PageSize wide"
  UIConstraints "*Duplex  *PageSize wide.bl"
  UIConstraints "*Duplex  *PageSize fineartletter"
  UIConstraints "*Duplex  *PageSize finearta4"

  UIConstraints "*MediaType prophoto *InputSlot front"
  UIConstraints "*MediaType superphoto *InputSlot front"
  UIConstraints "*MediaType glossygold *InputSlot front"
  UIConstraints "*MediaType doublesidephoto *InputSlot front"
  UIConstraints "*MediaType matte *InputSlot front"
  UIConstraints "*MediaType glossypaper *InputSlot front"
  UIConstraints "*MediaType highres *InputSlot front"
  UIConstraints "*MediaType ijpostcard *InputSlot front"
  UIConstraints "*MediaType postcard *InputSlot front"
  UIConstraints "*MediaType tshirt *InputSlot front"
  UIConstraints "*MediaType envelope *InputSlot front"
  UIConstraints "*MediaType otherphoto *InputSlot front"
  UIConstraints "*MediaType prophoto *InputSlot cassette"
  UIConstraints "*MediaType prophoto *InputSlot continuous"
  UIConstraints "*MediaType superphoto *InputSlot cassette"
  UIConstraints "*MediaType superphoto *InputSlot continuous"
  UIConstraints "*MediaType doublesidephoto *InputSlot cassette"
  UIConstraints "*MediaType doublesidephoto *InputSlot continuous"
  UIConstraints "*MediaType glossygold *InputSlot cassette"
  UIConstraints "*MediaType glossygold *InputSlot continuous"
  UIConstraints "*MediaType prophoto2 *InputSlot cassette"
  UIConstraints "*MediaType prophoto2 *InputSlot continuous"
  UIConstraints "*MediaType proplatinum *InputSlot cassette"
  UIConstraints "*MediaType proplatinum *InputSlot continuous"
  UIConstraints "*MediaType semigloss *InputSlot cassette"
  UIConstraints "*MediaType semigloss *InputSlot continuous"
  UIConstraints "*MediaType glossypaper *InputSlot cassette"
  UIConstraints "*MediaType glossypaper *InputSlot continuous"
  UIConstraints "*MediaType matte *InputSlot cassette"
  UIConstraints "*MediaType matte *InputSlot continuous"
  UIConstraints "*MediaType highres *InputSlot cassette"
  UIConstraints "*MediaType highres *InputSlot continuous"
  UIConstraints "*MediaType envelope *InputSlot cassette"
  UIConstraints "*MediaType envelope *InputSlot continuous"
  UIConstraints "*MediaType postcardaddress *InputSlot cassette"
  UIConstraints "*MediaType postcardaddress *InputSlot continuous"
  UIConstraints "*MediaType ijpostcard *InputSlot cassette"
  UIConstraints "*MediaType ijpostcard *InputSlot continuous"
  UIConstraints "*MediaType glossypost *InputSlot cassette"
  UIConstraints "*MediaType glossypost *InputSlot continuous"
  UIConstraints "*MediaType prophotopost *InputSlot cassette"
  UIConstraints "*MediaType prophotopost *InputSlot continuous"
  UIConstraints "*MediaType postcard *InputSlot cassette"
  UIConstraints "*MediaType postcard *InputSlot continuous"
  UIConstraints "*MediaType fineartphotorag *InputSlot cassette"
  UIConstraints "*MediaType fineartphotorag *InputSlot continuous"
  UIConstraints "*MediaType otherfineart *InputSlot cassette"
  UIConstraints "*MediaType otherfineart *InputSlot continuous"
  UIConstraints "*MediaType tshirt *InputSlot cassette"
  UIConstraints "*MediaType tshirt *InputSlot continuous"
  UIConstraints "*MediaType ohp *InputSlot cassette"
  UIConstraints "*MediaType ohp *InputSlot continuous"
  UIConstraints "*MediaType envelope *InputSlot cassette"
  UIConstraints "*MediaType envelope *InputSlot continuous"
  UIConstraints "*MediaType otherphoto *InputSlot cassette"
  UIConstraints "*MediaType otherphoto *InputSlot continuous"
  UIConstraints "*MediaType otherfineart *PageSize Letter.bl"
  UIConstraints "*MediaType otherfineart *PageSize A4.bl"
  UIConstraints "*MediaType otherfineart *PageSize 4X6.bl"
  UIConstraints "*MediaType otherfineart *PageSize 4X8.bl"
  UIConstraints "*MediaType otherfineart *PageSize 5X7.bl"
  UIConstraints "*MediaType otherfineart *PageSize 8X10.bl"
  UIConstraints "*MediaType otherfineart *PageSize l.bl"
  UIConstraints "*MediaType otherfineart *PageSize 2l.bl"
  UIConstraints "*MediaType otherfineart *PageSize postcard.bl"
  UIConstraints "*MediaType otherfineart *PageSize businesscard.bl"
  UIConstraints "*MediaType otherfineart *PageSize wide.bl"
  UIConstraints "*MediaType envelope *PageSize Letter.bl"
  UIConstraints "*MediaType envelope *PageSize ledger.bl"
  UIConstraints "*MediaType envelope *PageSize A4.bl"
  UIConstraints "*MediaType envelope *PageSize a3.bl"
  UIConstraints "*MediaType envelope *PageSize a3plus.bl"
  UIConstraints "*MediaType envelope *PageSize 4X6.bl"
  UIConstraints "*MediaType envelope *PageSize 4X8.bl"
  UIConstraints "*MediaType envelope *PageSize 5X7.bl"
  UIConstraints "*MediaType envelope *PageSize 8X10.bl"
  UIConstraints "*MediaType envelope *PageSize 10X12.bl"
  UIConstraints "*MediaType envelope *PageSize l.bl"
  UIConstraints "*MediaType envelope *PageSize 2l.bl"
  UIConstraints "*MediaType envelope *PageSize postcard.bl"
  UIConstraints "*MediaType envelope *PageSize creditcard.bl"
  UIConstraints "*MediaType envelope *PageSize businesscard.bl"
  UIConstraints "*MediaType envelope *PageSize wide.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize Letter.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize A4.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize 4X6.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize 4X8.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize 5X7.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize 8X10.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize l.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize 2l.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize postcard.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize businesscard.bl"
  UIConstraints "*MediaType fineartphotorag *PageSize wide.bl"
  UIConstraints "*MediaType highres *PageSize Letter.bl"
  UIConstraints "*MediaType highres *PageSize ledger.bl"
  UIConstraints "*MediaType highres *PageSize A4.bl"
  UIConstraints "*MediaType highres *PageSize a3.bl"
  UIConstraints "*MediaType highres *PageSize a3plus.bl"
  UIConstraints "*MediaType highres *PageSize 4X6.bl"
  UIConstraints "*MediaType highres *PageSize 4X8.bl"
  UIConstraints "*MediaType highres *PageSize 5X7.bl"
  UIConstraints "*MediaType highres *PageSize 8X10.bl"
  UIConstraints "*MediaType highres *PageSize 10X12.bl"
  UIConstraints "*MediaType highres *PageSize l.bl"
  UIConstraints "*MediaType highres *PageSize 2l.bl"
  UIConstraints "*MediaType highres *PageSize postcard.bl"
  UIConstraints "*MediaType highres *PageSize creditcard.bl"
  UIConstraints "*MediaType highres *PageSize businesscard.bl"
  UIConstraints "*MediaType highres *PageSize wide.bl"
  UIConstraints "*MediaType tshirt *PageSize Letter.bl"
  UIConstraints "*MediaType tshirt *PageSize ledger.bl"
  UIConstraints "*MediaType tshirt *PageSize A4.bl"
  UIConstraints "*MediaType tshirt *PageSize a3.bl"
  UIConstraints "*MediaType tshirt *PageSize a3plus.bl"
  UIConstraints "*MediaType tshirt *PageSize 4X6.bl"
  UIConstraints "*MediaType tshirt *PageSize 4X8.bl"
  UIConstraints "*MediaType tshirt *PageSize 5X7.bl"
  UIConstraints "*MediaType tshirt *PageSize 8X10.bl"
  UIConstraints "*MediaType tshirt *PageSize 10X12.bl"
  UIConstraints "*MediaType tshirt *PageSize l.bl"
  UIConstraints "*MediaType tshirt *PageSize 2l.bl"
  UIConstraints "*MediaType tshirt *PageSize postcard.bl"
  UIConstraints "*MediaType tshirt *PageSize creditcard.bl"
  UIConstraints "*MediaType tshirt *PageSize businesscard.bl"
  UIConstraints "*MediaType tshirt *PageSize wide.bl"




  Group "*CNMain/Main"
    Option "CNQuality/Print Quality" PickOne AnySetup 0,0
      Choice "1/1(High)" "<</CNQuality(1)>>setpagedevice"
      Choice "2/2" "<</CNQuality(2)>>setpagedevice"
      *Choice "3/3" "<</CNQuality(3)>>setpagedevice"
      Choice "4/4(Fast)" "<</CNQuality(4)>>setpagedevice"
    Option "CNGrayscale/Grayscale Printing" Boolean AnySetup 0,0
      Choice "True/ON" "<</CNGrayscale(True)>>setpagedevice"
      *Choice "False/OFF" "<</CNGrayscale(False)>>setpagedevice"
    Option "CNHalftoning/Halftoning" PickOne AnySetup 0,0
      *Choice "ed/Diffusion" "<</CNHalftoning(ed)>>setpagedevice"
      Choice "pattern/Dither" "<</CNHalftoning(pattern)>>setpagedevice"
    Option "CNRenderIntent/Vivid Photo" PickOne AnySetup 0,0
      *Choice "photo/Photo" "<</CNRenderIntent(photo)>>setpagedevice"
      Choice "vivid/Vivid" "<</CNRenderIntent(vivid)>>setpagedevice"

  Group "*CNColorAdjust/Manual Color Adjustment"
    Option "CNBalanceC/Cyan" PickOne AnySetup 0,0
      Choice "-50/-50" "<</CNBalanceC(-50)>>setpagedevice"
      Choice "-49/-49" "<</CNBalanceC(-49)>>setpagedevice"
      Choice "-48/-48" "<</CNBalanceC(-48)>>setpagedevice"
      Choice "-47/-47" "<</CNBalanceC(-47)>>setpagedevice"
      Choice "-46/-46" "<</CNBalanceC(-46)>>setpagedevice"
      Choice "-45/-45" "<</CNBalanceC(-45)>>setpagedevice"
      Choice "-44/-44" "<</CNBalanceC(-44)>>setpagedevice"
      Choice "-43/-43" "<</CNBalanceC(-43)>>setpagedevice"
      Choice "-42/-42" "<</CNBalanceC(-42)>>setpagedevice"
      Choice "-41/-41" "<</CNBalanceC(-41)>>setpagedevice"
      Choice "-40/-40" "<</CNBalanceC(-40)>>setpagedevice"
      Choice "-39/-39" "<</CNBalanceC(-39)>>setpagedevice"
      Choice "-38/-38" "<</CNBalanceC(-38)>>setpagedevice"
      Choice "-37/-37" "<</CNBalanceC(-37)>>setpagedevice"
      Choice "-36/-36" "<</CNBalanceC(-36)>>setpagedevice"
      Choice "-35/-35" "<</CNBalanceC(-35)>>setpagedevice"
      Choice "-34/-34" "<</CNBalanceC(-34)>>setpagedevice"
      Choice "-33/-33" "<</CNBalanceC(-33)>>setpagedevice"
      Choice "-32/-32" "<</CNBalanceC(-32)>>setpagedevice"
      Choice "-31/-31" "<</CNBalanceC(-31)>>setpagedevice"
      Choice "-30/-30" "<</CNBalanceC(-30)>>setpagedevice"
      Choice "-29/-29" "<</CNBalanceC(-29)>>setpagedevice"
      Choice "-28/-28" "<</CNBalanceC(-28)>>setpagedevice"
      Choice "-27/-27" "<</CNBalanceC(-27)>>setpagedevice"
      Choice "-26/-26" "<</CNBalanceC(-26)>>setpagedevice"
      Choice "-25/-25" "<</CNBalanceC(-25)>>setpagedevice"
      Choice "-24/-24" "<</CNBalanceC(-24)>>setpagedevice"
      Choice "-23/-23" "<</CNBalanceC(-23)>>setpagedevice"
      Choice "-22/-22" "<</CNBalanceC(-22)>>setpagedevice"
      Choice "-21/-21" "<</CNBalanceC(-21)>>setpagedevice"
      Choice "-20/-20" "<</CNBalanceC(-20)>>setpagedevice"
      Choice "-19/-19" "<</CNBalanceC(-19)>>setpagedevice"
      Choice "-18/-18" "<</CNBalanceC(-18)>>setpagedevice"
      Choice "-17/-17" "<</CNBalanceC(-17)>>setpagedevice"
      Choice "-16/-16" "<</CNBalanceC(-16)>>setpagedevice"
      Choice "-15/-15" "<</CNBalanceC(-15)>>setpagedevice"
      Choice "-14/-14" "<</CNBalanceC(-14)>>setpagedevice"
      Choice "-13/-13" "<</CNBalanceC(-13)>>setpagedevice"
      Choice "-12/-12" "<</CNBalanceC(-12)>>setpagedevice"
      Choice "-11/-11" "<</CNBalanceC(-11)>>setpagedevice"
      Choice "-10/-10" "<</CNBalanceC(-10)>>setpagedevice"
      Choice "-9/-9" "<</CNBalanceC(-9)>>setpagedevice"
      Choice "-8/-8" "<</CNBalanceC(-8)>>setpagedevice"
      Choice "-7/-7" "<</CNBalanceC(-7)>>setpagedevice"
      Choice "-6/-6" "<</CNBalanceC(-6)>>setpagedevice"
      Choice "-5/-5" "<</CNBalanceC(-5)>>setpagedevice"
      Choice "-4/-4" "<</CNBalanceC(-4)>>setpagedevice"
      Choice "-3/-3" "<</CNBalanceC(-3)>>setpagedevice"
      Choice "-2/-2" "<</CNBalanceC(-2)>>setpagedevice"
      Choice "-1/-1" "<</CNBalanceC(-1)>>setpagedevice"
      *Choice "0/0" "<</CNBalanceC(0)>>setpagedevice"
      Choice "1/1" "<</CNBalanceC(1)>>setpagedevice"
      Choice "2/2" "<</CNBalanceC(2)>>setpagedevice"
      Choice "3/3" "<</CNBalanceC(3)>>setpagedevice"
      Choice "4/4" "<</CNBalanceC(4)>>setpagedevice"
      Choice "5/5" "<</CNBalanceC(5)>>setpagedevice"
      Choice "6/6" "<</CNBalanceC(6)>>setpagedevice"
      Choice "7/7" "<</CNBalanceC(7)>>setpagedevice"
      Choice "8/8" "<</CNBalanceC(8)>>setpagedevice"
      Choice "9/9" "<</CNBalanceC(9)>>setpagedevice"
      Choice "10/10" "<</CNBalanceC(10)>>setpagedevice"
      Choice "11/11" "<</CNBalanceC(11)>>setpagedevice"
      Choice "12/12" "<</CNBalanceC(12)>>setpagedevice"
      Choice "13/13" "<</CNBalanceC(13)>>setpagedevice"
      Choice "14/14" "<</CNBalanceC(14)>>setpagedevice"
      Choice "15/15" "<</CNBalanceC(15)>>setpagedevice"
      Choice "16/16" "<</CNBalanceC(16)>>setpagedevice"
      Choice "17/17" "<</CNBalanceC(17)>>setpagedevice"
      Choice "18/18" "<</CNBalanceC(18)>>setpagedevice"
      Choice "19/19" "<</CNBalanceC(19)>>setpagedevice"
      Choice "20/20" "<</CNBalanceC(20)>>setpagedevice"
      Choice "21/21" "<</CNBalanceC(21)>>setpagedevice"
      Choice "22/22" "<</CNBalanceC(22)>>setpagedevice"
      Choice "23/23" "<</CNBalanceC(23)>>setpagedevice"
      Choice "24/24" "<</CNBalanceC(24)>>setpagedevice"
      Choice "25/25" "<</CNBalanceC(25)>>setpagedevice"
      Choice "26/26" "<</CNBalanceC(26)>>setpagedevice"
      Choice "27/27" "<</CNBalanceC(27)>>setpagedevice"
      Choice "28/28" "<</CNBalanceC(28)>>setpagedevice"
      Choice "29/29" "<</CNBalanceC(29)>>setpagedevice"
      Choice "30/30" "<</CNBalanceC(30)>>setpagedevice"
      Choice "31/31" "<</CNBalanceC(31)>>setpagedevice"
      Choice "32/32" "<</CNBalanceC(32)>>setpagedevice"
      Choice "33/33" "<</CNBalanceC(33)>>setpagedevice"
      Choice "34/34" "<</CNBalanceC(34)>>setpagedevice"
      Choice "35/35" "<</CNBalanceC(35)>>setpagedevice"
      Choice "36/36" "<</CNBalanceC(36)>>setpagedevice"
      Choice "37/37" "<</CNBalanceC(37)>>setpagedevice"
      Choice "38/38" "<</CNBalanceC(38)>>setpagedevice"
      Choice "39/39" "<</CNBalanceC(39)>>setpagedevice"
      Choice "40/40" "<</CNBalanceC(40)>>setpagedevice"
      Choice "41/41" "<</CNBalanceC(41)>>setpagedevice"
      Choice "42/42" "<</CNBalanceC(42)>>setpagedevice"
      Choice "43/43" "<</CNBalanceC(43)>>setpagedevice"
      Choice "44/44" "<</CNBalanceC(44)>>setpagedevice"
      Choice "45/45" "<</CNBalanceC(45)>>setpagedevice"
      Choice "46/46" "<</CNBalanceC(46)>>setpagedevice"
      Choice "47/47" "<</CNBalanceC(47)>>setpagedevice"
      Choice "48/48" "<</CNBalanceC(48)>>setpagedevice"
      Choice "49/49" "<</CNBalanceC(49)>>setpagedevice"
      Choice "50/50" "<</CNBalanceC(50)>>setpagedevice"
    Option "CNBalanceM/Magenta" PickOne AnySetup 0,0
      Choice "-50/-50" "<</CNBalanceM(-50)>>setpagedevice"
      Choice "-49/-49" "<</CNBalanceM(-49)>>setpagedevice"
      Choice "-48/-48" "<</CNBalanceM(-48)>>setpagedevice"
      Choice "-47/-47" "<</CNBalanceM(-47)>>setpagedevice"
      Choice "-46/-46" "<</CNBalanceM(-46)>>setpagedevice"
      Choice "-45/-45" "<</CNBalanceM(-45)>>setpagedevice"
      Choice "-44/-44" "<</CNBalanceM(-44)>>setpagedevice"
      Choice "-43/-43" "<</CNBalanceM(-43)>>setpagedevice"
      Choice "-42/-42" "<</CNBalanceM(-42)>>setpagedevice"
      Choice "-41/-41" "<</CNBalanceM(-41)>>setpagedevice"
      Choice "-40/-40" "<</CNBalanceM(-40)>>setpagedevice"
      Choice "-39/-39" "<</CNBalanceM(-39)>>setpagedevice"
      Choice "-38/-38" "<</CNBalanceM(-38)>>setpagedevice"
      Choice "-37/-37" "<</CNBalanceM(-37)>>setpagedevice"
      Choice "-36/-36" "<</CNBalanceM(-36)>>setpagedevice"
      Choice "-35/-35" "<</CNBalanceM(-35)>>setpagedevice"
      Choice "-34/-34" "<</CNBalanceM(-34)>>setpagedevice"
      Choice "-33/-33" "<</CNBalanceM(-33)>>setpagedevice"
      Choice "-32/-32" "<</CNBalanceM(-32)>>setpagedevice"
      Choice "-31/-31" "<</CNBalanceM(-31)>>setpagedevice"
      Choice "-30/-30" "<</CNBalanceM(-30)>>setpagedevice"
      Choice "-29/-29" "<</CNBalanceM(-29)>>setpagedevice"
      Choice "-28/-28" "<</CNBalanceM(-28)>>setpagedevice"
      Choice "-27/-27" "<</CNBalanceM(-27)>>setpagedevice"
      Choice "-26/-26" "<</CNBalanceM(-26)>>setpagedevice"
      Choice "-25/-25" "<</CNBalanceM(-25)>>setpagedevice"
      Choice "-24/-24" "<</CNBalanceM(-24)>>setpagedevice"
      Choice "-23/-23" "<</CNBalanceM(-23)>>setpagedevice"
      Choice "-22/-22" "<</CNBalanceM(-22)>>setpagedevice"
      Choice "-21/-21" "<</CNBalanceM(-21)>>setpagedevice"
      Choice "-20/-20" "<</CNBalanceM(-20)>>setpagedevice"
      Choice "-19/-19" "<</CNBalanceM(-19)>>setpagedevice"
      Choice "-18/-18" "<</CNBalanceM(-18)>>setpagedevice"
      Choice "-17/-17" "<</CNBalanceM(-17)>>setpagedevice"
      Choice "-16/-16" "<</CNBalanceM(-16)>>setpagedevice"
      Choice "-15/-15" "<</CNBalanceM(-15)>>setpagedevice"
      Choice "-14/-14" "<</CNBalanceM(-14)>>setpagedevice"
      Choice "-13/-13" "<</CNBalanceM(-13)>>setpagedevice"
      Choice "-12/-12" "<</CNBalanceM(-12)>>setpagedevice"
      Choice "-11/-11" "<</CNBalanceM(-11)>>setpagedevice"
      Choice "-10/-10" "<</CNBalanceM(-10)>>setpagedevice"
      Choice "-9/-9" "<</CNBalanceM(-9)>>setpagedevice"
      Choice "-8/-8" "<</CNBalanceM(-8)>>setpagedevice"
      Choice "-7/-7" "<</CNBalanceM(-7)>>setpagedevice"
      Choice "-6/-6" "<</CNBalanceM(-6)>>setpagedevice"
      Choice "-5/-5" "<</CNBalanceM(-5)>>setpagedevice"
      Choice "-4/-4" "<</CNBalanceM(-4)>>setpagedevice"
      Choice "-3/-3" "<</CNBalanceM(-3)>>setpagedevice"
      Choice "-2/-2" "<</CNBalanceM(-2)>>setpagedevice"
      Choice "-1/-1" "<</CNBalanceM(-1)>>setpagedevice"
      *Choice "0/0" "<</CNBalanceM(0)>>setpagedevice"
      Choice "1/1" "<</CNBalanceM(1)>>setpagedevice"
      Choice "2/2" "<</CNBalanceM(2)>>setpagedevice"
      Choice "3/3" "<</CNBalanceM(3)>>setpagedevice"
      Choice "4/4" "<</CNBalanceM(4)>>setpagedevice"
      Choice "5/5" "<</CNBalanceM(5)>>setpagedevice"
      Choice "6/6" "<</CNBalanceM(6)>>setpagedevice"
      Choice "7/7" "<</CNBalanceM(7)>>setpagedevice"
      Choice "8/8" "<</CNBalanceM(8)>>setpagedevice"
      Choice "9/9" "<</CNBalanceM(9)>>setpagedevice"
      Choice "10/10" "<</CNBalanceM(10)>>setpagedevice"
      Choice "11/11" "<</CNBalanceM(11)>>setpagedevice"
      Choice "12/12" "<</CNBalanceM(12)>>setpagedevice"
      Choice "13/13" "<</CNBalanceM(13)>>setpagedevice"
      Choice "14/14" "<</CNBalanceM(14)>>setpagedevice"
      Choice "15/15" "<</CNBalanceM(15)>>setpagedevice"
      Choice "16/16" "<</CNBalanceM(16)>>setpagedevice"
      Choice "17/17" "<</CNBalanceM(17)>>setpagedevice"
      Choice "18/18" "<</CNBalanceM(18)>>setpagedevice"
      Choice "19/19" "<</CNBalanceM(19)>>setpagedevice"
      Choice "20/20" "<</CNBalanceM(20)>>setpagedevice"
      Choice "21/21" "<</CNBalanceM(21)>>setpagedevice"
      Choice "22/22" "<</CNBalanceM(22)>>setpagedevice"
      Choice "23/23" "<</CNBalanceM(23)>>setpagedevice"
      Choice "24/24" "<</CNBalanceM(24)>>setpagedevice"
      Choice "25/25" "<</CNBalanceM(25)>>setpagedevice"
      Choice "26/26" "<</CNBalanceM(26)>>setpagedevice"
      Choice "27/27" "<</CNBalanceM(27)>>setpagedevice"
      Choice "28/28" "<</CNBalanceM(28)>>setpagedevice"
      Choice "29/29" "<</CNBalanceM(29)>>setpagedevice"
      Choice "30/30" "<</CNBalanceM(30)>>setpagedevice"
      Choice "31/31" "<</CNBalanceM(31)>>setpagedevice"
      Choice "32/32" "<</CNBalanceM(32)>>setpagedevice"
      Choice "33/33" "<</CNBalanceM(33)>>setpagedevice"
      Choice "34/34" "<</CNBalanceM(34)>>setpagedevice"
      Choice "35/35" "<</CNBalanceM(35)>>setpagedevice"
      Choice "36/36" "<</CNBalanceM(36)>>setpagedevice"
      Choice "37/37" "<</CNBalanceM(37)>>setpagedevice"
      Choice "38/38" "<</CNBalanceM(38)>>setpagedevice"
      Choice "39/39" "<</CNBalanceM(39)>>setpagedevice"
      Choice "40/40" "<</CNBalanceM(40)>>setpagedevice"
      Choice "41/41" "<</CNBalanceM(41)>>setpagedevice"
      Choice "42/42" "<</CNBalanceM(42)>>setpagedevice"
      Choice "43/43" "<</CNBalanceM(43)>>setpagedevice"
      Choice "44/44" "<</CNBalanceM(44)>>setpagedevice"
      Choice "45/45" "<</CNBalanceM(45)>>setpagedevice"
      Choice "46/46" "<</CNBalanceM(46)>>setpagedevice"
      Choice "47/47" "<</CNBalanceM(47)>>setpagedevice"
      Choice "48/48" "<</CNBalanceM(48)>>setpagedevice"
      Choice "49/49" "<</CNBalanceM(49)>>setpagedevice"
      Choice "50/50" "<</CNBalanceM(50)>>setpagedevice"
    Option "CNBalanceY/Yellow" PickOne AnySetup 0,0
      Choice "-50/-50" "<</CNBalanceY(-50)>>setpagedevice"
      Choice "-49/-49" "<</CNBalanceY(-49)>>setpagedevice"
      Choice "-48/-48" "<</CNBalanceY(-48)>>setpagedevice"
      Choice "-47/-47" "<</CNBalanceY(-47)>>setpagedevice"
      Choice "-46/-46" "<</CNBalanceY(-46)>>setpagedevice"
      Choice "-45/-45" "<</CNBalanceY(-45)>>setpagedevice"
      Choice "-44/-44" "<</CNBalanceY(-44)>>setpagedevice"
      Choice "-43/-43" "<</CNBalanceY(-43)>>setpagedevice"
      Choice "-42/-42" "<</CNBalanceY(-42)>>setpagedevice"
      Choice "-41/-41" "<</CNBalanceY(-41)>>setpagedevice"
      Choice "-40/-40" "<</CNBalanceY(-40)>>setpagedevice"
      Choice "-39/-39" "<</CNBalanceY(-39)>>setpagedevice"
      Choice "-38/-38" "<</CNBalanceY(-38)>>setpagedevice"
      Choice "-37/-37" "<</CNBalanceY(-37)>>setpagedevice"
      Choice "-36/-36" "<</CNBalanceY(-36)>>setpagedevice"
      Choice "-35/-35" "<</CNBalanceY(-35)>>setpagedevice"
      Choice "-34/-34" "<</CNBalanceY(-34)>>setpagedevice"
      Choice "-33/-33" "<</CNBalanceY(-33)>>setpagedevice"
      Choice "-32/-32" "<</CNBalanceY(-32)>>setpagedevice"
      Choice "-31/-31" "<</CNBalanceY(-31)>>setpagedevice"
      Choice "-30/-30" "<</CNBalanceY(-30)>>setpagedevice"
      Choice "-29/-29" "<</CNBalanceY(-29)>>setpagedevice"
      Choice "-28/-28" "<</CNBalanceY(-28)>>setpagedevice"
      Choice "-27/-27" "<</CNBalanceY(-27)>>setpagedevice"
      Choice "-26/-26" "<</CNBalanceY(-26)>>setpagedevice"
      Choice "-25/-25" "<</CNBalanceY(-25)>>setpagedevice"
      Choice "-24/-24" "<</CNBalanceY(-24)>>setpagedevice"
      Choice "-23/-23" "<</CNBalanceY(-23)>>setpagedevice"
      Choice "-22/-22" "<</CNBalanceY(-22)>>setpagedevice"
      Choice "-21/-21" "<</CNBalanceY(-21)>>setpagedevice"
      Choice "-20/-20" "<</CNBalanceY(-20)>>setpagedevice"
      Choice "-19/-19" "<</CNBalanceY(-19)>>setpagedevice"
      Choice "-18/-18" "<</CNBalanceY(-18)>>setpagedevice"
      Choice "-17/-17" "<</CNBalanceY(-17)>>setpagedevice"
      Choice "-16/-16" "<</CNBalanceY(-16)>>setpagedevice"
      Choice "-15/-15" "<</CNBalanceY(-15)>>setpagedevice"
      Choice "-14/-14" "<</CNBalanceY(-14)>>setpagedevice"
      Choice "-13/-13" "<</CNBalanceY(-13)>>setpagedevice"
      Choice "-12/-12" "<</CNBalanceY(-12)>>setpagedevice"
      Choice "-11/-11" "<</CNBalanceY(-11)>>setpagedevice"
      Choice "-10/-10" "<</CNBalanceY(-10)>>setpagedevice"
      Choice "-9/-9" "<</CNBalanceY(-9)>>setpagedevice"
      Choice "-8/-8" "<</CNBalanceY(-8)>>setpagedevice"
      Choice "-7/-7" "<</CNBalanceY(-7)>>setpagedevice"
      Choice "-6/-6" "<</CNBalanceY(-6)>>setpagedevice"
      Choice "-5/-5" "<</CNBalanceY(-5)>>setpagedevice"
      Choice "-4/-4" "<</CNBalanceY(-4)>>setpagedevice"
      Choice "-3/-3" "<</CNBalanceY(-3)>>setpagedevice"
      Choice "-2/-2" "<</CNBalanceY(-2)>>setpagedevice"
      Choice "-1/-1" "<</CNBalanceY(-1)>>setpagedevice"
      *Choice "0/0" "<</CNBalanceY(0)>>setpagedevice"
      Choice "1/1" "<</CNBalanceY(1)>>setpagedevice"
      Choice "2/2" "<</CNBalanceY(2)>>setpagedevice"
      Choice "3/3" "<</CNBalanceY(3)>>setpagedevice"
      Choice "4/4" "<</CNBalanceY(4)>>setpagedevice"
      Choice "5/5" "<</CNBalanceY(5)>>setpagedevice"
      Choice "6/6" "<</CNBalanceY(6)>>setpagedevice"
      Choice "7/7" "<</CNBalanceY(7)>>setpagedevice"
      Choice "8/8" "<</CNBalanceY(8)>>setpagedevice"
      Choice "9/9" "<</CNBalanceY(9)>>setpagedevice"
      Choice "10/10" "<</CNBalanceY(10)>>setpagedevice"
      Choice "11/11" "<</CNBalanceY(11)>>setpagedevice"
      Choice "12/12" "<</CNBalanceY(12)>>setpagedevice"
      Choice "13/13" "<</CNBalanceY(13)>>setpagedevice"
      Choice "14/14" "<</CNBalanceY(14)>>setpagedevice"
      Choice "15/15" "<</CNBalanceY(15)>>setpagedevice"
      Choice "16/16" "<</CNBalanceY(16)>>setpagedevice"
      Choice "17/17" "<</CNBalanceY(17)>>setpagedevice"
      Choice "18/18" "<</CNBalanceY(18)>>setpagedevice"
      Choice "19/19" "<</CNBalanceY(19)>>setpagedevice"
      Choice "20/20" "<</CNBalanceY(20)>>setpagedevice"
      Choice "21/21" "<</CNBalanceY(21)>>setpagedevice"
      Choice "22/22" "<</CNBalanceY(22)>>setpagedevice"
      Choice "23/23" "<</CNBalanceY(23)>>setpagedevice"
      Choice "24/24" "<</CNBalanceY(24)>>setpagedevice"
      Choice "25/25" "<</CNBalanceY(25)>>setpagedevice"
      Choice "26/26" "<</CNBalanceY(26)>>setpagedevice"
      Choice "27/27" "<</CNBalanceY(27)>>setpagedevice"
      Choice "28/28" "<</CNBalanceY(28)>>setpagedevice"
      Choice "29/29" "<</CNBalanceY(29)>>setpagedevice"
      Choice "30/30" "<</CNBalanceY(30)>>setpagedevice"
      Choice "31/31" "<</CNBalanceY(31)>>setpagedevice"
      Choice "32/32" "<</CNBalanceY(32)>>setpagedevice"
      Choice "33/33" "<</CNBalanceY(33)>>setpagedevice"
      Choice "34/34" "<</CNBalanceY(34)>>setpagedevice"
      Choice "35/35" "<</CNBalanceY(35)>>setpagedevice"
      Choice "36/36" "<</CNBalanceY(36)>>setpagedevice"
      Choice "37/37" "<</CNBalanceY(37)>>setpagedevice"
      Choice "38/38" "<</CNBalanceY(38)>>setpagedevice"
      Choice "39/39" "<</CNBalanceY(39)>>setpagedevice"
      Choice "40/40" "<</CNBalanceY(40)>>setpagedevice"
      Choice "41/41" "<</CNBalanceY(41)>>setpagedevice"
      Choice "42/42" "<</CNBalanceY(42)>>setpagedevice"
      Choice "43/43" "<</CNBalanceY(43)>>setpagedevice"
      Choice "44/44" "<</CNBalanceY(44)>>setpagedevice"
      Choice "45/45" "<</CNBalanceY(45)>>setpagedevice"
      Choice "46/46" "<</CNBalanceY(46)>>setpagedevice"
      Choice "47/47" "<</CNBalanceY(47)>>setpagedevice"
      Choice "48/48" "<</CNBalanceY(48)>>setpagedevice"
      Choice "49/49" "<</CNBalanceY(49)>>setpagedevice"
      Choice "50/50" "<</CNBalanceY(50)>>setpagedevice"

    Option "CNGamma/Brightness" PickOne AnySetup 0,0
      Choice "1.4/Light" "<</CNGamma(1.4)>>setpagedevice"
      *Choice "1.8/Normal" "<</CNGamma(1.8)>>setpagedevice"
      Choice "2.2/Dark" "<</CNGamma(2.2)>>setpagedevice"

    Option "CNDensity/Intensity" PickOne AnySetup 0,0
      Choice "-50/-50" "<</CNDensity(-50)>>setpagedevice"
      Choice "-49/-49" "<</CNDensity(-49)>>setpagedevice"
      Choice "-48/-48" "<</CNDensity(-48)>>setpagedevice"
      Choice "-47/-47" "<</CNDensity(-47)>>setpagedevice"
      Choice "-46/-46" "<</CNDensity(-46)>>setpagedevice"
      Choice "-45/-45" "<</CNDensity(-45)>>setpagedevice"
      Choice "-44/-44" "<</CNDensity(-44)>>setpagedevice"
      Choice "-43/-43" "<</CNDensity(-43)>>setpagedevice"
      Choice "-42/-42" "<</CNDensity(-42)>>setpagedevice"
      Choice "-41/-41" "<</CNDensity(-41)>>setpagedevice"
      Choice "-40/-40" "<</CNDensity(-40)>>setpagedevice"
      Choice "-39/-39" "<</CNDensity(-39)>>setpagedevice"
      Choice "-38/-38" "<</CNDensity(-38)>>setpagedevice"
      Choice "-37/-37" "<</CNDensity(-37)>>setpagedevice"
      Choice "-36/-36" "<</CNDensity(-36)>>setpagedevice"
      Choice "-35/-35" "<</CNDensity(-35)>>setpagedevice"
      Choice "-34/-34" "<</CNDensity(-34)>>setpagedevice"
      Choice "-33/-33" "<</CNDensity(-33)>>setpagedevice"
      Choice "-32/-32" "<</CNDensity(-32)>>setpagedevice"
      Choice "-31/-31" "<</CNDensity(-31)>>setpagedevice"
      Choice "-30/-30" "<</CNDensity(-30)>>setpagedevice"
      Choice "-29/-29" "<</CNDensity(-29)>>setpagedevice"
      Choice "-28/-28" "<</CNDensity(-28)>>setpagedevice"
      Choice "-27/-27" "<</CNDensity(-27)>>setpagedevice"
      Choice "-26/-26" "<</CNDensity(-26)>>setpagedevice"
      Choice "-25/-25" "<</CNDensity(-25)>>setpagedevice"
      Choice "-24/-24" "<</CNDensity(-24)>>setpagedevice"
      Choice "-23/-23" "<</CNDensity(-23)>>setpagedevice"
      Choice "-22/-22" "<</CNDensity(-22)>>setpagedevice"
      Choice "-21/-21" "<</CNDensity(-21)>>setpagedevice"
      Choice "-20/-20" "<</CNDensity(-20)>>setpagedevice"
      Choice "-19/-19" "<</CNDensity(-19)>>setpagedevice"
      Choice "-18/-18" "<</CNDensity(-18)>>setpagedevice"
      Choice "-17/-17" "<</CNDensity(-17)>>setpagedevice"
      Choice "-16/-16" "<</CNDensity(-16)>>setpagedevice"
      Choice "-15/-15" "<</CNDensity(-15)>>setpagedevice"
      Choice "-14/-14" "<</CNDensity(-14)>>setpagedevice"
      Choice "-13/-13" "<</CNDensity(-13)>>setpagedevice"
      Choice "-12/-12" "<</CNDensity(-12)>>setpagedevice"
      Choice "-11/-11" "<</CNDensity(-11)>>setpagedevice"
      Choice "-10/-10" "<</CNDensity(-10)>>setpagedevice"
      Choice "-9/-9" "<</CNDensity(-9)>>setpagedevice"
      Choice "-8/-8" "<</CNDensity(-8)>>setpagedevice"
      Choice "-7/-7" "<</CNDensity(-7)>>setpagedevice"
      Choice "-6/-6" "<</CNDensity(-6)>>setpagedevice"
      Choice "-5/-5" "<</CNDensity(-5)>>setpagedevice"
      Choice "-4/-4" "<</CNDensity(-4)>>setpagedevice"
      Choice "-3/-3" "<</CNDensity(-3)>>setpagedevice"
      Choice "-2/-2" "<</CNDensity(-2)>>setpagedevice"
      Choice "-1/-1" "<</CNDensity(-1)>>setpagedevice"
      *Choice "0/0" "<</CNDensity(0)>>setpagedevice"
      Choice "1/1" "<</CNDensity(1)>>setpagedevice"
      Choice "2/2" "<</CNDensity(2)>>setpagedevice"
      Choice "3/3" "<</CNDensity(3)>>setpagedevice"
      Choice "4/4" "<</CNDensity(4)>>setpagedevice"
      Choice "5/5" "<</CNDensity(5)>>setpagedevice"
      Choice "6/6" "<</CNDensity(6)>>setpagedevice"
      Choice "7/7" "<</CNDensity(7)>>setpagedevice"
      Choice "8/8" "<</CNDensity(8)>>setpagedevice"
      Choice "9/9" "<</CNDensity(9)>>setpagedevice"
      Choice "10/10" "<</CNDensity(10)>>setpagedevice"
      Choice "11/11" "<</CNDensity(11)>>setpagedevice"
      Choice "12/12" "<</CNDensity(12)>>setpagedevice"
      Choice "13/13" "<</CNDensity(13)>>setpagedevice"
      Choice "14/14" "<</CNDensity(14)>>setpagedevice"
      Choice "15/15" "<</CNDensity(15)>>setpagedevice"
      Choice "16/16" "<</CNDensity(16)>>setpagedevice"
      Choice "17/17" "<</CNDensity(17)>>setpagedevice"
      Choice "18/18" "<</CNDensity(18)>>setpagedevice"
      Choice "19/19" "<</CNDensity(19)>>setpagedevice"
      Choice "20/20" "<</CNDensity(20)>>setpagedevice"
      Choice "21/21" "<</CNDensity(21)>>setpagedevice"
      Choice "22/22" "<</CNDensity(22)>>setpagedevice"
      Choice "23/23" "<</CNDensity(23)>>setpagedevice"
      Choice "24/24" "<</CNDensity(24)>>setpagedevice"
      Choice "25/25" "<</CNDensity(25)>>setpagedevice"
      Choice "26/26" "<</CNDensity(26)>>setpagedevice"
      Choice "27/27" "<</CNDensity(27)>>setpagedevice"
      Choice "28/28" "<</CNDensity(28)>>setpagedevice"
      Choice "29/29" "<</CNDensity(29)>>setpagedevice"
      Choice "30/30" "<</CNDensity(30)>>setpagedevice"
      Choice "31/31" "<</CNDensity(31)>>setpagedevice"
      Choice "32/32" "<</CNDensity(32)>>setpagedevice"
      Choice "33/33" "<</CNDensity(33)>>setpagedevice"
      Choice "34/34" "<</CNDensity(34)>>setpagedevice"
      Choice "35/35" "<</CNDensity(35)>>setpagedevice"
      Choice "36/36" "<</CNDensity(36)>>setpagedevice"
      Choice "37/37" "<</CNDensity(37)>>setpagedevice"
      Choice "38/38" "<</CNDensity(38)>>setpagedevice"
      Choice "39/39" "<</CNDensity(39)>>setpagedevice"
      Choice "40/40" "<</CNDensity(40)>>setpagedevice"
      Choice "41/41" "<</CNDensity(41)>>setpagedevice"
      Choice "42/42" "<</CNDensity(42)>>setpagedevice"
      Choice "43/43" "<</CNDensity(43)>>setpagedevice"
      Choice "44/44" "<</CNDensity(44)>>setpagedevice"
      Choice "45/45" "<</CNDensity(45)>>setpagedevice"
      Choice "46/46" "<</CNDensity(46)>>setpagedevice"
      Choice "47/47" "<</CNDensity(47)>>setpagedevice"
      Choice "48/48" "<</CNDensity(48)>>setpagedevice"
      Choice "49/49" "<</CNDensity(49)>>setpagedevice"
      Choice "50/50" "<</CNDensity(50)>>setpagedevice"
    Option "CNContrast/Contrast" PickOne AnySetup 0,0
      Choice "-50/-50" "<</CNContrast(-50)>>setpagedevice"
      Choice "-49/-49" "<</CNContrast(-49)>>setpagedevice"
      Choice "-48/-48" "<</CNContrast(-48)>>setpagedevice"
      Choice "-47/-47" "<</CNContrast(-47)>>setpagedevice"
      Choice "-46/-46" "<</CNContrast(-46)>>setpagedevice"
      Choice "-45/-45" "<</CNContrast(-45)>>setpagedevice"
      Choice "-44/-44" "<</CNContrast(-44)>>setpagedevice"
      Choice "-43/-43" "<</CNContrast(-43)>>setpagedevice"
      Choice "-42/-42" "<</CNContrast(-42)>>setpagedevice"
      Choice "-41/-41" "<</CNContrast(-41)>>setpagedevice"
      Choice "-40/-40" "<</CNContrast(-40)>>setpagedevice"
      Choice "-39/-39" "<</CNContrast(-39)>>setpagedevice"
      Choice "-38/-38" "<</CNContrast(-38)>>setpagedevice"
      Choice "-37/-37" "<</CNContrast(-37)>>setpagedevice"
      Choice "-36/-36" "<</CNContrast(-36)>>setpagedevice"
      Choice "-35/-35" "<</CNContrast(-35)>>setpagedevice"
      Choice "-34/-34" "<</CNContrast(-34)>>setpagedevice"
      Choice "-33/-33" "<</CNContrast(-33)>>setpagedevice"
      Choice "-32/-32" "<</CNContrast(-32)>>setpagedevice"
      Choice "-31/-31" "<</CNContrast(-31)>>setpagedevice"
      Choice "-30/-30" "<</CNContrast(-30)>>setpagedevice"
      Choice "-29/-29" "<</CNContrast(-29)>>setpagedevice"
      Choice "-28/-28" "<</CNContrast(-28)>>setpagedevice"
      Choice "-27/-27" "<</CNContrast(-27)>>setpagedevice"
      Choice "-26/-26" "<</CNContrast(-26)>>setpagedevice"
      Choice "-25/-25" "<</CNContrast(-25)>>setpagedevice"
      Choice "-24/-24" "<</CNContrast(-24)>>setpagedevice"
      Choice "-23/-23" "<</CNContrast(-23)>>setpagedevice"
      Choice "-22/-22" "<</CNContrast(-22)>>setpagedevice"
      Choice "-21/-21" "<</CNContrast(-21)>>setpagedevice"
      Choice "-20/-20" "<</CNContrast(-20)>>setpagedevice"
      Choice "-19/-19" "<</CNContrast(-19)>>setpagedevice"
      Choice "-18/-18" "<</CNContrast(-18)>>setpagedevice"
      Choice "-17/-17" "<</CNContrast(-17)>>setpagedevice"
      Choice "-16/-16" "<</CNContrast(-16)>>setpagedevice"
      Choice "-15/-15" "<</CNContrast(-15)>>setpagedevice"
      Choice "-14/-14" "<</CNContrast(-14)>>setpagedevice"
      Choice "-13/-13" "<</CNContrast(-13)>>setpagedevice"
      Choice "-12/-12" "<</CNContrast(-12)>>setpagedevice"
      Choice "-11/-11" "<</CNContrast(-11)>>setpagedevice"
      Choice "-10/-10" "<</CNContrast(-10)>>setpagedevice"
      Choice "-9/-9" "<</CNContrast(-9)>>setpagedevice"
      Choice "-8/-8" "<</CNContrast(-8)>>setpagedevice"
      Choice "-7/-7" "<</CNContrast(-7)>>setpagedevice"
      Choice "-6/-6" "<</CNContrast(-6)>>setpagedevice"
      Choice "-5/-5" "<</CNContrast(-5)>>setpagedevice"
      Choice "-4/-4" "<</CNContrast(-4)>>setpagedevice"
      Choice "-3/-3" "<</CNContrast(-3)>>setpagedevice"
      Choice "-2/-2" "<</CNContrast(-2)>>setpagedevice"
      Choice "-1/-1" "<</CNContrast(-1)>>setpagedevice"
      *Choice "0/0" "<</CNContrast(0)>>setpagedevice"
      Choice "1/1" "<</CNContrast(1)>>setpagedevice"
      Choice "2/2" "<</CNContrast(2)>>setpagedevice"
      Choice "3/3" "<</CNContrast(3)>>setpagedevice"
      Choice "4/4" "<</CNContrast(4)>>setpagedevice"
      Choice "5/5" "<</CNContrast(5)>>setpagedevice"
      Choice "6/6" "<</CNContrast(6)>>setpagedevice"
      Choice "7/7" "<</CNContrast(7)>>setpagedevice"
      Choice "8/8" "<</CNContrast(8)>>setpagedevice"
      Choice "9/9" "<</CNContrast(9)>>setpagedevice"
      Choice "10/10" "<</CNContrast(10)>>setpagedevice"
      Choice "11/11" "<</CNContrast(11)>>setpagedevice"
      Choice "12/12" "<</CNContrast(12)>>setpagedevice"
      Choice "13/13" "<</CNContrast(13)>>setpagedevice"
      Choice "14/14" "<</CNContrast(14)>>setpagedevice"
      Choice "15/15" "<</CNContrast(15)>>setpagedevice"
      Choice "16/16" "<</CNContrast(16)>>setpagedevice"
      Choice "17/17" "<</CNContrast(17)>>setpagedevice"
      Choice "18/18" "<</CNContrast(18)>>setpagedevice"
      Choice "19/19" "<</CNContrast(19)>>setpagedevice"
      Choice "20/20" "<</CNContrast(20)>>setpagedevice"
      Choice "21/21" "<</CNContrast(21)>>setpagedevice"
      Choice "22/22" "<</CNContrast(22)>>setpagedevice"
      Choice "23/23" "<</CNContrast(23)>>setpagedevice"
      Choice "24/24" "<</CNContrast(24)>>setpagedevice"
      Choice "25/25" "<</CNContrast(25)>>setpagedevice"
      Choice "26/26" "<</CNContrast(26)>>setpagedevice"
      Choice "27/27" "<</CNContrast(27)>>setpagedevice"
      Choice "28/28" "<</CNContrast(28)>>setpagedevice"
      Choice "29/29" "<</CNContrast(29)>>setpagedevice"
      Choice "30/30" "<</CNContrast(30)>>setpagedevice"
      Choice "31/31" "<</CNContrast(31)>>setpagedevice"
      Choice "32/32" "<</CNContrast(32)>>setpagedevice"
      Choice "33/33" "<</CNContrast(33)>>setpagedevice"
      Choice "34/34" "<</CNContrast(34)>>setpagedevice"
      Choice "35/35" "<</CNContrast(35)>>setpagedevice"
      Choice "36/36" "<</CNContrast(36)>>setpagedevice"
      Choice "37/37" "<</CNContrast(37)>>setpagedevice"
      Choice "38/38" "<</CNContrast(38)>>setpagedevice"
      Choice "39/39" "<</CNContrast(39)>>setpagedevice"
      Choice "40/40" "<</CNContrast(40)>>setpagedevice"
      Choice "41/41" "<</CNContrast(41)>>setpagedevice"
      Choice "42/42" "<</CNContrast(42)>>setpagedevice"
      Choice "43/43" "<</CNContrast(43)>>setpagedevice"
      Choice "44/44" "<</CNContrast(44)>>setpagedevice"
      Choice "45/45" "<</CNContrast(45)>>setpagedevice"
      Choice "46/46" "<</CNContrast(46)>>setpagedevice"
      Choice "47/47" "<</CNContrast(47)>>setpagedevice"
      Choice "48/48" "<</CNContrast(48)>>setpagedevice"
      Choice "49/49" "<</CNContrast(49)>>setpagedevice"
      Choice "50/50" "<</CNContrast(50)>>setpagedevice"
#endif

